Source/Eto.WinForms/Forms/Controls/ListBoxHandler.cs
Compiles and visually tested with `Eto.Test.WinForms.exe`
=> WinForms: Makes ListBox support TextBinding and ImageBinding

Source/Eto.Gtk/Forms/Controls/DropDownHandler.cs, Source/Eto.Gtk/Forms/Controls/ListBoxHandler.cs, Source/Eto.Mac/Forms/Controls/ComboBoxHandler.cs, Source/Eto.Mac/Forms/Controls/DropDownHandler.cs, Source/Eto.Mac/Forms/Controls/ListBoxHandler.cs, Source/Eto.Test/Eto.Test/Sections/Behaviors/DynamicMenuBar.cs, Source/Eto.WinForms/Forms/Controls/ComboBoxHandler.cs, Source/Eto.WinForms/Forms/Controls/DropDownHandler.cs, Source/Eto.WinForms/Forms/Controls/ListBoxHandler.cs, Source/Eto.Wpf/Forms/Controls/ComboBoxHandler.cs, Source/Eto.Wpf/Forms/Controls/DropDownHandler.cs, Source/Eto.Wpf/Forms/Controls/ListBoxHandler.cs, Source/Eto/Forms/Controls/ListBox.cs, Source/Eto/Forms/Controls/ListControl.cs, Source/Eto/Forms/Controls/RadioButtonList.cs, Source/Eto/Forms/ListItem.cs
API rename prefixes "Item" for TextBinding / KeyBinding / ImageBinding on list-able controls
=> API rename prefixes "Item" for TextBinding / KeyBinding / ImageBinding

Source/Eto.Gtk/Forms/Controls/GridHandler.cs, Source/Eto.Mac/Forms/Controls/GridViewHandler.cs, Source/Eto.Mac/Forms/Controls/TreeGridViewHandler.cs, Source/Eto.Test/Eto.Test/Sections/Controls/GridViewSection.cs, Source/Eto.Test/Eto.Test/Sections/Controls/TreeGridViewSection.cs, Source/Eto.Wpf/Forms/Controls/GridHandler.cs
Implemented CellClick on Wpf and Gtk.
This implements the missing events that are mentioned #271.
=> Implemented CellClick on Wpf ,Gtk and Mac.

Source/Eto.Gtk/Forms/Controls/GridHandler.cs, Source/Eto.Gtk/Forms/Controls/TreeGridViewHandler.cs
I have added the ability to select a row with SelectRow(int row) in Gtk.
I have tested this against the Wpf test application and it behaves the same.
Also there was a bug when calling GetRowIndexOfPath from TreeGridView In Gtk but it is now fixed.
=> Implemented GetIterAtRow and GetPathAtRow on Gtk.

Source/Eto.Gtk/Forms/Controls/GridViewHandler.cs, Source/Eto.Gtk/Forms/Controls/TreeGridViewHandler.cs
Implemented SetSelectedRows in TreeGridView on Gtk.
Also fixed a bug with SetSelectedRows in GridView on Gtk.
=> Implemented SetSelectedRows in TreeGridView on Gtk.

Source/Eto.Wpf/Forms/Controls/GridHandler.cs
I've introduced a bug when adding cell click to wpf.
This fixes it.
=> Fixed bug with cell click event in Wpf

Source/Eto.Gtk/Eto.Gtk2 - net45.csproj, Source/Eto.Gtk/Eto.Gtk2.csproj, Source/Eto.Gtk/Eto.Gtk3 - net45.csproj, Source/Eto.Gtk/Eto.Gtk3.csproj, Source/Eto.Gtk/Forms/Cells/ProgressCellHandler.cs, Source/Eto.Gtk/Platform.cs, Source/Eto.Mac/Eto.Mac - net45.csproj, Source/Eto.Mac/Eto.Mac.csproj, Source/Eto.Mac/Eto.Mac64 - net45.csproj, Source/Eto.Mac/Eto.Mac64.csproj, Source/Eto.Mac/Eto.XamMac - net45.csproj, Source/Eto.Mac/Eto.XamMac.csproj, Source/Eto.Mac/Eto.XamMac2.csproj, Source/Eto.Mac/Forms/Cells/ProgressCellHandler.cs, Source/Eto.Mac/Platform.cs, Source/Eto.Test/Eto.Test/Sections/Controls/GridViewSection.cs, Source/Eto.WinForms/Eto.WinForms - net45.csproj, Source/Eto.WinForms/Eto.WinForms.csproj, Source/Eto.WinForms/Forms/Cells/ProgressCellHandler.cs, Source/Eto.WinForms/Platform.cs, Source/Eto.Wpf/Eto.Wpf - net45.csproj, Source/Eto.Wpf/Eto.Wpf.csproj, Source/Eto.Wpf/Forms/Cells/ProgressCellHandler.cs, Source/Eto.Wpf/Platform.cs, Source/Eto/Eto - pcl.csproj, Source/Eto/Eto.csproj, Source/Eto/Forms/Cells/ProgressCell.cs
I also added a progress cell column to the gridview section in the test application.
@cwensley I made a PR.
=> Added ProgressCell to Wpf, WinForms, Gtk, Mac

Source/Eto.Gtk/Forms/Cells/ProgressCellHandler.cs, Source/Eto.Mac/Forms/Cells/ProgressCellHandler.cs, Source/Eto.Test/Eto.Test/Sections/Controls/GridViewSection.cs, Source/Eto.WinForms/Forms/Cells/ProgressCellHandler.cs, Source/Eto.Wpf/Forms/Cells/ProgressCellHandler.cs, Source/Eto/Forms/Cells/ProgressCell.cs
Min value is forced to -1.
Max value is forced to 100.
Also I added that when the value is -1 it doesn't draw the ProgressCell.
=> Refined ProgressCell.

Source/Eto.Gtk/Forms/GtkWindow.cs, Source/Eto.Test/Eto.Test/Sections/Behaviors/WindowsSection.cs, Source/Eto/Forms/Dialog.cs, Source/Eto/Forms/Form.cs, Source/Eto/Forms/Window.cs
Setup parent when using Dialog.ShowModal
=> Add Window.Owner. Patch for Issue #319

Source/Eto/Drawing/Color.cs, Source/Eto/Drawing/ColorConverter.cs, Source/Eto/Drawing/PaddingConverter.cs, Source/Eto/Drawing/PointConverter.cs, Source/Eto/Drawing/PointFConverter.cs, Source/Eto/Drawing/RectangleConverter.cs, Source/Eto/Drawing/RectangleFConverter.cs, Source/Eto/Drawing/SizeConverter.cs, Source/Eto/Drawing/SizeFConverter.cs, Source/Eto/Forms/Dialog.cs, Source/Shared/Conversions.cs
Changed string to char and cleanup Color and ColorConverter. These are the missing changes form the #332-pull request.
=> Converter changes

Source/Eto.Gtk/Forms/GtkFileDialog.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/picoe/eto/399)
=> Implement Gtk file filters

Source/Eto.WinForms/Forms/Controls/GridViewHandler.cs, Source/Eto.Wpf/Forms/Controls/GridHandler.cs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/picoe/eto/404)
=> Fix two OutOfRange exceptions in GridView

Source/Eto.Designer/Builders/CodeInterfaceBuilder.cs
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/picoe/eto/470)
=> Implement detecting reference assemblies path on Linux

Source/Eto.Gtk/Forms/Menu/ButtonMenuItemHandler.cs
This fixes 2 things:
1. Clearing items now actually removes submenu items instead of deleting the label of the main menuitem...
2. Adds a ButtonRelease event to workaround Gtk ContextMenu bug that's been out for years. Basically what it does is makes you unable to select submenu items of context menu
- https://bugzilla.gnome.org/show_bug.cgi?id=695488
- http://stackoverflow.com/questions/5221326/submenu-item-does-not-call-function-with-working-solution
=> Fix Context Menu Submenu and Clearing Items

Source/Eto.Gtk/Forms/Menu/ButtonMenuItemHandler.cs
It was possible for both events to occur, only one needs to occur.
=> Fix ContextMenu

Source/Eto.Gtk/Eto.Gtk2 - net45.csproj, Source/Eto.Gtk/Eto.Gtk3 - net45.csproj, Source/Eto.Mac/Eto.Mac - net45.csproj, Source/Eto.Mac/Eto.Mac64 - net45.csproj, Source/Eto.Mac/Eto.XamMac - net45.csproj, Source/Eto.Mac/Eto.XamMac2 - mobile.csproj, Source/Eto.Mac/Eto.XamMac2 - net45.csproj, Source/Eto.Serialization.Json/Eto.Serialization.Json - net45.csproj, Source/Eto.Serialization.Json/Eto.Serialization.Json - pcl.csproj, Source/Eto.Serialization.Xaml/DesignerUserControl.cs, Source/Eto.Serialization.Xaml/Eto.Serialization.Xaml - pcl.csproj, Source/Eto.Serialization.Xaml/EtoXamlType.cs, Source/Eto.WinForms/Eto.WinForms - net45.csproj, Source/Eto.WinForms/Forms/FormHandler.cs, Source/Eto.Wpf/Eto.Wpf - net45.csproj, Source/Eto/Eto - pcl.csproj
Because warnings are evil. (;
Also: Update Xamarin Studio 6.1 formatting policy noise in project files while I'm at it.
=> Treat warnings as errors and fix a few warnings.

Source/Eto.Gtk/Forms/Controls/DropDownHandler.cs
Fixes: #512
For DropDown no mouse events worked.
For ComboBox only mouse move event worked.
=> Gtk Add Combobox and DropDown to Eventbox so mouse events occur

Source/Eto.Test/Eto.Test/UnitTests/Forms/DataContextTests.cs, Source/Eto/Forms/Binding/BindableWidget.cs, Source/Eto/Forms/Binding/DualBinding.cs, Source/Eto/Forms/Binding/ObjectBinding.cs, Source/Eto/Forms/Binding/PropertyBinding.cs
=> Fix databinding

Source/Eto.Gtk/Forms/Controls/SliderHandler.cs, Source/Eto.Mac/Forms/Controls/SliderHandler.cs, Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj, Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/SliderTests.cs
=> Gtk/Mac: Allow Slider.TickFrequency to be set to zero

Source/Eto.Test/Eto.Test/UnitTests/Forms/WindowTests.cs, Source/Eto.Test/Eto.Test/UnitTests/TestBase.cs, Source/Eto/EventLookup.cs
=> Fix registering override events with multiple subclasses.

Source/Eto.Mac/Drawing/IndexedBitmapHandler.cs
Due to recent changes to check for multiple calls to Bitmap.Lock(), it now requires the widget and can’t be used from the handler alone.
=> Mac: Fix regression when drawing IndexedBitmap

Source/Eto.Serialization.Xaml/Eto.Serialization.Xaml - pcl.csproj, Source/Eto.Serialization.Xaml/EtoXamlSchemaContext.cs, Source/Eto.Serialization.Xaml/EtoXamlType.cs, Source/Eto.Serialization.Xaml/Extensions/BindingExtension.cs, Source/Eto.Serialization.Xaml/Extensions/StaticResourceExtension.cs, Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj, Source/Eto.Test/Eto.Test/Sections/Serialization/Xaml/Test.cs, Source/Eto.Test/Eto.Test/Sections/Serialization/Xaml/Test.xeto, Source/Eto.Test/Eto.Test/UnitTests/Forms/Binding/ObjectBindingChangedTests.cs, Source/Eto.Test/Eto.Test/UnitTests/Forms/Binding/PropertyBindingTests.cs, Source/Eto/Eto - pcl.csproj, Source/Eto/Forms/Binding/BindableBinding.cs, Source/Eto/Forms/Binding/BindableExtensions.cs, Source/Eto/Forms/Binding/Binding.helpers.cs, Source/Eto/Forms/Binding/DirectBinding.cs, Source/Eto/Forms/Binding/IValueConverter.cs, Source/Eto/Forms/Binding/IndirectBinding.cs, Source/Eto/Forms/Binding/ObjectBinding.cs, Source/Eto/Forms/Binding/PropertyBinding.cs, Source/Eto/Forms/Cells/CheckBoxCell.cs, Source/Eto/Forms/Cells/ComboBoxCell.cs, Source/Eto/Forms/Cells/ImageTextCell.cs, Source/Eto/Forms/Cells/ImageViewCell.cs, Source/Eto/Forms/Cells/ProgressCell.cs, Source/Eto/Forms/Cells/TextBoxCell.cs
In progress work for binding updates to fix #439
=> Binding Updates

Source/Eto.Gtk/Forms/MouseHandler.cs, Source/Eto.Mac/Forms/MouseHandler.cs, Source/Eto.Test/Eto.Test/Sections/Behaviors/MousePositionSection.cs, Source/Eto.WinForms/Forms/MouseHandler.cs, Source/Eto.Wpf/Forms/MouseHandler.cs, Source/Eto/Forms/Mouse.cs
Not 100% sure if this works correctly on Gtk with multiple monitor setup.
=> Add ability to set Mouse.Position.

Source/Eto.Gtk/Eto.Gtk2 - net45.csproj, Source/Eto.Gtk/Eto.Gtk3 - net45.csproj, Source/Eto.Gtk/Forms/ColorDialogHandler.cs, Source/Eto.Gtk/Forms/ColorDialogHandlerGtk34.cs, Source/Eto.Gtk/Forms/FontDialogHandlerGtk32.cs, Source/Eto.Gtk/NativeMethods.cs, Source/Eto.Gtk/Platform.cs, Source/Eto.NativeGtk/Eto.NativeGtk - net45.csproj
Implements the new FontChooserDialog: https://developer.gnome.org/gtk3/stable/GtkFontChooserDialog.html
PS. I also fixed up some code formatting in ColorChooser.
=> [Gtk] Implement the new FontChooserDialog

Source/Eto.Gtk/Eto.Gtk3 - net45.csproj, Source/Eto.Gtk/Forms/OpenWithDialogHandler.cs, Source/Eto.Gtk/NativeMethods.cs, Source/Eto.Gtk/Platform.cs, Source/Eto.NativeGtk/Eto.NativeGtk - net45.csproj, Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj, Source/Eto.Test/Eto.Test/Sections/Dialogs/OpenWithDialogSection.cs, Source/Eto.WinForms/Eto.WinForms - net45.csproj, Source/Eto.WinForms/Forms/OpenWithDialogHandler.cs, Source/Eto.WinForms/Platform.cs, Source/Eto.Wpf/Eto.Wpf - net45.csproj, Source/Eto.Wpf/Forms/OpenWithDialogHandler.cs, Source/Eto.Wpf/Platform.cs, Source/Eto/Eto - pcl.csproj, Source/Eto/Forms/OpenWithDialog.cs
Only implemented for Gtk3, WinForms and WPF backends.
=> Implement OpenWithDialog

Source/Eto.Test/Eto.Test/Sections/Drawing/BitmapSection.cs
=> Add test for scaled images using the Bitmap constructor

Source/Eto.Wpf/Forms/Controls/ScrollableHandler.cs
- Defer setting content size to measure/arrange of scrollable so that we don’t cause an infinite loop.
- No longer need a hack when in a GroupBox and should be more resilient to other issues.
Fixes #477
Fixes #638
Fixes #552
=> Wpf: Fix Scrollable infinite sizing loop

Source/Eto.Gtk/Forms/SelectFolderDialogHandler.cs, Source/Eto.Test/Eto.Test/Sections/Dialogs/SelectFolderSection.cs, Source/Eto.WinForms/Eto.WinForms - net45.csproj, Source/Eto.WinForms/Platform.cs, Source/Eto.WinForms/WinFormsHelpers.cs, Source/Eto.Wpf/Eto.Wpf - net45.csproj, Source/Eto.Wpf/Forms/VistaSelectFolderDialogHandler.cs, Source/Eto.Wpf/Platform.cs, Source/Eto.Wpf/WpfHelpers.cs, Source/Eto.Wpf/packages.config
- For both Wpf/WinForms, will fall back to old implementation for platforms that do not support it.
Fixes #559
=> Use Vista-style dialog for SelectFolderDialog on Windows.

appveyor.yml
=> Update appveyor to build 2.4.0-buildXXX nuget packages.

Source/Eto.Wpf/Forms/WpfContainer.cs, Source/Eto.Wpf/Forms/WpfFrameworkElement.cs
..instead of only when we have infinite space.
=> Wpf: Container.MinimumSize calculation properly handled

Source/Eto.Gtk/Forms/Controls/LabelHandler.cs
=> fixes Gtk2 label size and wrap issues

Source/Eto.Gtk/Eto.Gtk2 - net45.csproj, Source/Eto.Gtk/Eto.Gtk3 - net45.csproj, Source/Eto.Gtk/Forms/Controls/DocumentControlHandler.cs, Source/Eto.Gtk/Forms/Controls/DocumentPageHandler.cs, Source/Eto.Gtk/Platform.cs, Source/Eto.NativeGtk/Eto.NativeGtk - net45.csproj, Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj, Source/Eto.Test/Eto.Test/Sections/Controls/DocumentControlSection.cs, Source/Eto/Eto - pcl.csproj, Source/Eto/Forms/Controls/DocumentControl.cs, Source/Eto/Forms/Controls/DocumentPage.cs
I'll work on a themed implementation of this in a separate PR.
Edit: Since I forgot to mention, a good chunk of code came from TabControl.
=> DocumentControl and DocumentPage Gtk Implementations

Source/Eto.Mac/Eto.Mac - net45.csproj, Source/Eto.Mac/Eto.Mac64 - net45.csproj, Source/Eto.Mac/Eto.XamMac - net45.csproj, Source/Eto.Mac/Eto.XamMac2 - net45.csproj, Source/Eto.Mac/Forms/OpenWithDialogHandler.cs, Source/Eto.Mac/Platform.cs
=> [Mac] OpenWithDialogHandler

Source/Eto.Gtk/Forms/Controls/RadioButtonHandler.cs, Source/Eto/Forms/Controls/RadioButtonList.cs
This is a partial fix, but need to ensure that RadioButtonHandler.Text is called when the Text of a RadioButton is changed.
=> [Gtk] RadioButton shows partial Label when Text is empty #715

Source/Eto.Gtk/Eto.Gtk2 - net45.csproj, Source/Eto.Gtk/Eto.Gtk3 - net45.csproj, Source/Eto.Gtk/Forms/ApplicationHandler.cs, Source/Eto.Gtk/Forms/GtkWindow.cs, Source/Eto.Gtk/Forms/LinuxNotificationHandler.cs, Source/Eto.Gtk/Forms/LinuxTrayIndicatorHandler.cs, Source/Eto.Gtk/Platform.cs, Source/Eto.NativeGtk/Eto.NativeGtk - net45.csproj, Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj, Source/Eto.Test/Eto.Test/MainForm.cs, Source/Eto.Test/Eto.Test/Sections/Behaviors/NotificationSection.cs, Source/Eto.WinForms/Eto.WinForms - net45.csproj, Source/Eto.WinForms/Forms/NotificationHandler.cs, Source/Eto.WinForms/Platform.cs, Source/Eto.Wpf/Eto.Wpf - net45.csproj, Source/Eto.Wpf/Forms/NotificationHandler.cs, Source/Eto.Wpf/Platform.cs, Source/Eto/Eto - pcl.csproj, Source/Eto/Forms/Notification.cs, Source/Eto/Forms/TrayIndicator.cs
Notes:
- Gtk does not have a way of showing notifications on Windows and Mac
- Someone else can add Windows 10 notification manager to WPF, for now it only has the standard way of using the StatusIcon to show notifications
=> Notification Implementation [Gtk, WPF, WinForms]

Source/Eto.Gtk/Forms/DialogHandler.cs, Source/Eto.Gtk/Forms/GtkWindow.cs
Sorry about doing a rebase, found a bug in my code.
=> [Gtk] Fix dialog sizing

Source/Eto.Gtk/Forms/ApplicationHandler.cs, Source/Eto.Gtk/Forms/LinuxNotificationHandler.cs
=> [Gtk] Add init check to NotificationHandler

Source/Eto.Gtk/Forms/LinuxNotificationHandler.cs
Turns out we need to check ntofication server capabilities before showing the notification with actions, otherwise we get a messagebox... go figure :)
=> Fix Notifications not working on Ubuntu

Source/Eto.Gtk/Drawing/BitmapHandler.cs, Source/Eto.Gtk/Drawing/GraphicsHandler.cs, Source/Eto.Gtk/Forms/Controls/DrawableHandler.cs, Source/Eto.Gtk/NativeMethods.cs, Source/Eto.Gtk/NativeMethods.tt, Source/Eto.Test/Eto.Test/Sections/Drawing/TextureBrushesSection2.cs
=> Gtk: Make drawing to a Bitmap using Graphics orders of magnitude faster

Source/Eto.Wpf/Forms/ApplicationHandler.cs
=> Removed hardcoded assembly name in Eto.Wpf #567

Source/Eto.Gtk/Forms/Controls/GridHandler.cs, Source/Eto.Gtk/Forms/Controls/GridViewHandler.cs, Source/Eto.Mac/Forms/Cells/CheckBoxCellHandler.cs, Source/Eto.Mac/Forms/Cells/ComboBoxCellHandler.cs, Source/Eto.Mac/Forms/Cells/CustomCellHandler.cs, Source/Eto.Mac/Forms/Cells/ImageTextCellHandler.cs, Source/Eto.Mac/Forms/Cells/TextBoxCellHandler.cs, Source/Eto.Mac/Forms/Controls/GridColumnHandler.cs, Source/Eto.Mac/Forms/Controls/GridHandler.cs, Source/Eto.Mac/Forms/Controls/GridViewHandler.cs, Source/Eto.Mac/Forms/Controls/MacLabel.cs, Source/Eto.Test/Eto.Test/Sections/Controls/GridViewSection.cs, Source/Eto.Test/Eto.Test/UnitTests/Handlers/Controls/TestGridViewHandler.cs, Source/Eto.WinForms/Forms/Controls/GridHandler.cs, Source/Eto.WinForms/Forms/Controls/GridViewHandler.cs, Source/Eto.Wpf/Forms/ApplicationHandler.cs, Source/Eto.Wpf/Forms/Controls/GridHandler.cs, Source/Eto.Wpf/Forms/Controls/GridViewHandler.cs, Source/Eto/Forms/Controls/Grid.cs, Source/Eto/Forms/Controls/GridView.cs, Source/Eto/Forms/Controls/TreeGridView.cs
Add GridView.GetCellAt()
Add GridView.CommitEdit and CancelEdit
Mac: Fix editing text columns in a Grid.
Mac: Optimize the ComboBoxCell to reduce allocations to string
Wpf: Fix applying default styles to ApplicationHandler
=> GridView enhancements

Source/Eto.Gtk/Forms/Controls/GridHandler.cs, Source/Eto.Gtk/Forms/GtkControl.cs, Source/Eto.Gtk/GtkConversions.cs, Source/Eto.Mac/Forms/Cells/CheckBoxCellHandler.cs, Source/Eto.Mac/Forms/Cells/ComboBoxCellHandler.cs, Source/Eto.Mac/Forms/Cells/ImageTextCellHandler.cs, Source/Eto.Mac/Forms/Cells/TextBoxCellHandler.cs, Source/Eto.Mac/Forms/Controls/GridHandler.cs, Source/Eto.Mac/Forms/Controls/GridViewHandler.cs, Source/Eto.Mac/Forms/Controls/TreeGridViewHandler.cs, Source/Eto.Mac/Forms/MacView.cs, Source/Eto.Mac/MacConversions.cs, Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj, Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/ControlTests.cs, Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/GridViewTests.cs, Source/Eto.Test/Eto.Test/UnitTests/TestBase.cs, Source/Eto.WinForms/Forms/Controls/GridHandler.cs, Source/Eto.WinForms/Forms/MouseHandler.cs, Source/Eto.WinForms/WinConversions.cs, Source/Eto.Wpf/Forms/Controls/GridHandler.cs, Source/Eto.Wpf/Forms/WpfFrameworkElement.cs, Source/Eto.Wpf/WpfConversions.cs, Source/Eto/Forms/Controls/Grid.cs, Source/Eto/Forms/Controls/GridView.cs
.. and call event for other mouse buttons (not just primary).
=> Add mouse & modifier info to Grid.CellClick/CellDoubleClick

Source/Eto.Gtk/Forms/Controls/NumericStepperHandler.cs, Source/Eto.Mac/Forms/Cells/CheckBoxCellHandler.cs, Source/Eto.Mac/Forms/Cells/ComboBoxCellHandler.cs, Source/Eto.Mac/Forms/Cells/DrawableCellHandler.cs, Source/Eto.Mac/Forms/Cells/ImageTextCellHandler.cs, Source/Eto.Mac/Forms/Cells/TextBoxCellHandler.cs, Source/Eto.Mac/Forms/Controls/NumericStepperHandler.cs, Source/Eto.Mac/Messaging.cs, Source/Eto.Test/Eto.Test/Sections/Controls/NumericStepperSection.cs, Source/Eto.WinForms/Forms/Controls/NumericStepperHandler.cs, Source/Eto.Wpf/Forms/Controls/NumericStepperHandler.cs, Source/Eto/Forms/Binding/BindableBinding.cs, Source/Eto/Forms/Binding/DirectBinding.cs, Source/Eto/Forms/Binding/IndirectBinding.cs, Source/Eto/Forms/Controls/NumericStepper.cs
You can now have a completely custom format or use different culture than the current culture.
Also added CatchException<T>() helpers for binding so you can handle exceptions when setting binding values.
=> Add NumericStepper.CultureInfo and FormatString.

Source/Eto.Gtk/Forms/Cells/ImageTextCellHandler.cs, Source/Eto.Gtk/Forms/Cells/TextBoxCellHandler.cs, Source/Eto.Gtk/Forms/Controls/TextBoxHandler.cs, Source/Eto.Mac/Forms/Cells/CellHandler.cs, Source/Eto.Mac/Forms/Cells/ImageTextCellHandler.cs, Source/Eto.Mac/Forms/Cells/TextBoxCellHandler.cs, Source/Eto.Mac/Forms/Controls/MacText.cs, Source/Eto.Mac/Forms/Controls/TextBoxHandler.cs, Source/Eto.Test/Eto.Test/Sections/Controls/GridViewSection.cs, Source/Eto.Test/Eto.Test/UnitTests/Handlers/Cells/TestTextBoxCellHandler.cs, Source/Eto.WinForms/Forms/Cells/ImageTextCellHandler.cs, Source/Eto.WinForms/Forms/Cells/TextBoxCellHandler.cs, Source/Eto.WinForms/Forms/Controls/TextBoxHandler.cs, Source/Eto.Wpf/Forms/Cells/ImageTextCellHandler.cs, Source/Eto.Wpf/Forms/Cells/TextBoxCellHandler.cs, Source/Eto.Wpf/Forms/Controls/TextBoxHandler.cs, Source/Eto.Wpf/Forms/WpfWindow.cs, Source/Eto/Forms/Cells/ImageTextCell.cs, Source/Eto/Forms/Cells/TextBoxCell.cs, Source/Eto/Forms/Controls/TextBox.cs
- Add AutoSelectMode.Always to always select all even when clicking on the text.
- Add AutoSelectMode to TextBoxCell and ImageTextCell.
=> AutoSelectMode enhancements

Source/Eto.Gtk/Forms/Controls/SplitterHandler.cs
=> Gtk: Fix resizing a Form with a Splitter on macOS.

Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj, Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/TreeGridViewTests.cs
=> Fix infinite loop with TreeGridView.SelectedItems

Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/TreeGridViewTests.cs, Source/Eto.Wpf/WpfExtensions.cs
=> Wpf: Fix crash when content element has focus

Source/Eto.Wpf/Eto.Wpf - net45.csproj, Source/Eto.Wpf/Forms/Controls/TextBoxHandler.cs, Source/Eto.Wpf/Forms/Controls/TextStepperHandler.cs, Source/Eto.Wpf/packages.config
WPF: PlaceholderText now shows even when the control has focus
=> Update Wpf Tookit to 3.1

Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/TreeGridViewTests.cs, Source/Eto.Wpf/CustomControls/TreeGridView/TreeToggleButton.cs
=> Wpf: Content of TreeGridView's first column should expand to fill.

Source/Eto.Wpf/Forms/DialogHandler.cs
I don't know if this will work for everyone, but this works for me
=> Make Wpf DialogHandler more extendable

Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
When composing text using the Windows IME (e.g. for Japanese, Chinese, etc), it doesn't appear to use the selection attributes to enter the text.
This fixes it via a hack to update the attributes after the composition is finished.
Unfortunately, there doesn't seem to be a way to apply the attributes beforehand so when composing it uses the current attributes.
=> Wpf: Fix selection attributes when using a composition (IME)

Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
When composing text using the IME, only the last section of text was updated to the correct attributes.
Now it updates as you type and also will apply the formatting correctly to the entire string.
=> Wpf: Fix RichTextArea's selection attributes when using compositions

Source/Eto.Mac/Forms/MacWindow.cs
=> Mac: Fix potential NRE crash when getting the field editor for a window.

Source/Eto.Test/Eto.Test/UnitTests/Forms/FilterCollectionTests.cs, Source/Eto/Forms/FilterCollection.cs
- When removing or adding items to the source list while the filter collection had a filter or sort, it would revert after the filter is changed the items and external list would get out of sync.
- Optimized changes so it does not create new objects/delegates each time a change occurs
- CopyTo() did nothing if there was no filter
- ICollection.CopyTo wasn't implemented even though it was easy to do so
=> FilterCollection fixes

Source/Eto.Wpf/Forms/WindowsFormsHostHandler.cs, Source/Eto.Wpf/Forms/WpfFrameworkElement.cs
Forward more functionality to WinFormsControl, such as Focus, HasFocus, Invalidate, Enabled, SuspendLayout, ResumeLayout, and AllowDrop.
=> WinFormsHostHandler updates.

src/Eto.Wpf/Forms/ApplicationHandler.cs
Use InvokeIfNecessary based on significant performance gain using
moderately complex test application.
=> Change Invoke to improve performance

src/Eto.Wpf/Forms/ApplicationHandler.cs
=> Wpf: Set main form when it changes

src/Eto/Eto.csproj, src/Eto/Forms/Controls/Grid.cs
- Also added VS for mac formatting policy to Eto.csproj
=> Add Grid.SelectedRow for easier binding to a single row.

samples/Tutorials/FSharp/Tutorial4/Program.fs
=> Fix F# sample

src/Eto/Forms/Binding/IndirectBinding.cs
=> Look at Cancel flag for IndirectBinding.SetValue

samples/Tutorials/CSharp/Tutorial1/CS.Tutorial1.HelloWorld.csproj, samples/Tutorials/CSharp/Tutorial2/CS.Tutorial2.MenusAndToolbars.csproj, samples/Tutorials/CSharp/Tutorial3/CS.Tutorial3.TableLayout.csproj, samples/Tutorials/CSharp/Tutorial4/CS.Tutorial4.Binding.csproj, samples/Tutorials/FSharp/Tutorial1/FS.Tutorial1.HelloWorld.fsproj, samples/Tutorials/FSharp/Tutorial2/FS.Tutorial2.MenusAndToolbars.fsproj, samples/Tutorials/FSharp/Tutorial3/FS.Tutorial3.TableLayout.fsproj, samples/Tutorials/FSharp/Tutorial4/FS.Tutorial4.Binding.fsproj
=> F# and C# Tutorials should output to different assembly names.

build/Build.proj, samples/Samples.sln, samples/Tutorials/CSharp/Tutorial1/CS.Tutorial1.HelloWorld.csproj, samples/Tutorials/CSharp/Tutorial2/CS.Tutorial2.MenusAndToolbars.csproj, samples/Tutorials/CSharp/Tutorial3/CS.Tutorial3.TableLayout.csproj, samples/Tutorials/CSharp/Tutorial4/CS.Tutorial4.Binding.csproj, samples/Tutorials/FSharp/Tutorial1/FS.Tutorial1.HelloWorld.fsproj, samples/Tutorials/FSharp/Tutorial2/FS.Tutorial2.MenusAndToolbars.fsproj, samples/Tutorials/FSharp/Tutorial3/FS.Tutorial3.TableLayout.fsproj, samples/Tutorials/FSharp/Tutorial4/FS.Tutorial4.Binding.fsproj
- Fixes using F# tutorials on VS 2017
=> Use sdk-style projects for tutorials

src/Eto.Mac/AsyncQueue.cs, src/Eto.Mac/Eto.Mac.csproj, src/Eto.Mac/Eto.Mac64.csproj, src/Eto.Mac/Eto.XamMac.csproj, src/Eto.Mac/Eto.XamMac2-modern.csproj, src/Eto.Mac/Eto.XamMac2-net45.csproj, src/Eto.Mac/Forms/Controls/DrawableHandler.cs, src/Eto.Mac/Forms/Controls/DropDownHandler.cs, src/Eto.Mac/Forms/Controls/TextAreaHandler.cs, src/Eto.Mac/Forms/MacContainer.cs, src/Eto.Mac/Forms/MacView.cs, src/Eto.Mac/Forms/TableLayoutHandler.cs
Mac: Optimize TableLayout when multiple controls trigger a new layout pass.
Mac: Use a queue to trigger OnFocus
Mac: Support setting TextArea.Font to null for binding scenarios
Mac: Optimize adding a large amount of items to a DropDown
=> Mac optimizations

src/Eto.Mac/Forms/Menu/ButtonMenuItemHandler.cs, src/Eto.Mac/Forms/Menu/CheckMenuItemHandler.cs, src/Eto.Mac/Forms/Menu/MenuBarHandler.cs, src/Eto.Mac/Forms/Menu/MenuHandler.cs, src/Eto.Mac/Forms/Menu/RadioMenuItemHandler.cs, src/Eto.Mac/Forms/Menu/SeparatorMenuItem.cs, test/Eto.Test/MainForm.cs
=> Mac: Fix enabled items after dialog is shown

src/Eto.Gtk/Forms/Controls/TabControlHandler.cs, src/Eto/Forms/Controls/TabControl.cs, test/Eto.Test/Sections/Controls/TabControlSection.cs
=> Gtk: Fix TabControl.Pages.Clear()

src/Eto/Forms/Controls/RadioButtonList.cs, test/Eto.Test/Sections/Controls/RadioButtonListSection.cs
=> Add RadioButtonList.TextColor

src/Eto.Mac/Forms/Controls/GridHandler.cs, src/Eto.Mac/Forms/Controls/GridViewHandler.cs, src/Eto.Mac/Forms/Controls/TreeGridViewHandler.cs, test/Eto.Test/Sections/Controls/TreeGridViewSection.cs
=> Mac: Fix SelectedRow/Item in ContextMenu in GridView/TreeGridView

src/Addins/Eto.Addin.VisualStudio/source.extension.vsixmanifest, src/Addins/Eto.Designer/AppDomainDesignHost.cs
=> Fix crashing with preview in VS 15.6

src/Eto.Gtk/Forms/Printing/PrintDialogHandler.cs, src/Eto.Gtk/NativeMethods.cs, src/Eto.Gtk/NativeMethods.tt
I have added few lines of code that allow for selecting page size and orientation for GTK 2 or GTK 3.
=> GTK 2/3 Embed PageSetup

src/Eto.Mac/Forms/Controls/DrawableHandler.cs, src/Eto.Mac/Forms/Controls/ExpanderHandler.cs, src/Eto.Mac/Forms/Controls/GroupBoxHandler.cs, src/Eto.Mac/Forms/Controls/PanelHandler.cs, src/Eto.Mac/Forms/Controls/ScrollableHandler.cs, src/Eto.Mac/Forms/Controls/TabPageHandler.cs, src/Eto.Mac/Forms/DialogHandler.cs, src/Eto.Mac/Forms/MacPanel.cs, src/Eto.Mac/Forms/MacWindow.cs, src/Eto.Mac/Forms/TableLayoutHandler.cs, src/Eto.Mac/Mac64Extensions.cs, test/Eto.Test/UnitTests/Forms/DialogTests.cs
- Move layout logic into handlers so it can be overridden
- Allow content frame to be adjusted (e.g. for Dialog)
- Add a manual test for Dialog to ensure content is shown correctly.
=> Mac: Fix layout with Dialog/Form

appveyor.yml
=> Update CI version to 2.5.x

src/Eto.Mac/Forms/MacWindow.cs, src/Eto.Mac/MacHelpers.cs, src/Eto/Forms/Layout/StackLayout.cs
- Fix Window.Location when size of the form is changed after OnLoad
- Fix NRE with GetFieldEditor when controls are disposed
- Misc update: Add constructor to StackLayout that takes an (params) array of items.
=> Fix Mac Window.location and NRE with GetFieldEditor

src/Eto.Gtk/Forms/ApplicationHandler.cs
This fixes the missing implementation of Restart() in Gtk.
=> Gtk: Fix missing Application.Restart()

src/Eto.Mac/Forms/NativeFormHandler.cs, src/Eto.WinForms/Forms/HwndFormHandler.cs, src/Eto.WinForms/Win32.cs
Allow access to Location, Size, and Visible properties.
=> Mac/Wpf: Add ability to get native window's properties.

src/Eto.Mac/Drawing/FontTypefaceHandler.cs, test/Eto.Test.Mac/Eto.Test.XamMac.csproj, test/Eto.Test.Mac/packages.config
.. also update Eto.Test.XamMac to NUnit 3.10.1
=>  Mac: Use CoreText to get font name (it's faster)

src/Eto/Forms/Window.cs
=> Add note about LSUIElement for Window.ShowInTaskbar

src/Eto.Wpf/CustomControls/HttpServer.cs
Used when serving local content to WebView on Windows.
Fixes #1158
=> Add svg support to HttpServer

src/Eto/Forms/Controls/Grid.cs
=> Fix comment for Grid.SelectedRows

src/Eto.Mac/KeyMap.cs
=> Fix key mappings on Xamarin.Mac.

src/Eto.Gtk/Forms/Controls/CheckBoxHandler.cs, src/Eto.Gtk/Forms/Controls/GroupBoxHandler.cs, src/Eto.Wpf/Forms/Controls/GroupBoxHandler.cs, test/Eto.Test/UnitTests/Forms/Controls/ControlTests.cs
- Wpf: GroupBox
- Gtk: GroupBox & CheckBox
- Added tests
Fixes #1052
=> Font property should return a value

src/Eto.Gtk/Forms/Controls/TextBoxHandler.cs, src/Eto.Mac/Forms/Controls/TextBoxHandler.cs, src/Eto.Mac/Forms/MacFieldEditor.cs, src/Eto.WinForms/Forms/Controls/TextBoxHandler.cs, src/Eto.Wpf/Forms/Controls/TextBoxHandler.cs, src/Eto/Forms/Cells/PropertyCell.cs, src/Eto/Forms/Controls/MaskedTextBox.cs, src/Eto/Forms/Controls/MaskedTextStepper.cs, src/Eto/Forms/Controls/TextChangingEventArgs.cs, test/Eto.Test/UnitTests/Forms/Controls/TextBoxTests.cs, test/Eto.Test/UnitTests/Forms/Controls/TextChangingEventArgsTests.cs
- Fixes issues with MaskedTextBox/Stepper when updating text.
=> We need to know if TextChanging was fired from user input or programmatically

build/nuspec/Eto.Serialization.Xaml.nuspec, src/Addins/Eto.Addin.VisualStudio/Eto.Addin.VisualStudio.csproj, src/Eto.Serialization.Xaml/Eto.Serialization.Xaml.csproj, test/Eto.Test.Mac/Eto.Test.XamMac.csproj, test/Eto.Test.Mac/packages.config
=> Update Portable.Xaml to 0.23

build/MacTemplate/MacTemplate.targets, src/Eto.Mac/Platform.cs, src/Eto.sln
- Embeds mono and all your assemblies in one executable in the .app bundle
- Supports building on Linux and Windows too!
=> Add mkbundle support to build macOS .app bundles

src/Eto.Mac/Forms/ToolBar/CheckToolItemHandler.cs, src/Eto.Mac/Forms/ToolBar/RadioToolItemHandler.cs
=> Properly fire CheckToolItem.CheckedChanged on Mac.

src/Eto.Mac/Forms/Cells/TextBoxCellHandler.cs
=> Mac: Fix TextBoxCell when value is null.

src/Eto.Mac/Forms/ApplicationHandler.cs
=> Mac: Implement Application.UnhandledException
