picoe/Eto

Source/Eto.Gtk/Forms/Controls/GridHandler.cs
Source/Eto.Gtk/Forms/Controls/GridViewHandler.cs
Source/Eto.Mac/Forms/Controls/GridHandler.cs
Source/Eto.Mac/Forms/Controls/GridViewHandler.cs
Source/Eto.WinForms/Forms/Controls/GridHandler.cs
Source/Eto.WinForms/Forms/Controls/GridViewHandler.cs
Source/Eto.Wpf/Forms/Controls/GridHandler.cs
Source/Eto.Wpf/Forms/Controls/GridViewHandler.cs
Source/Eto/Forms/Controls/Grid.cs
Source/Eto/Forms/Controls/GridView.cs

This is my first pull request so any tips are welcome. :)
This moves the events CellClick and CellDoubleClick from GridView to Grid.
It also moves the event implementations from GridViewHandler to GridHandler for
the following platforms. WinForms, Wpf, Gtk, Mac
fixes #271 
It doesn't implement the CellClick and CellDoubleClick events in GridHandler in the platforms that miss it.
We can create a new issue for that.
Platforms that have CellClick:
- WinForms
Platforms that have CellDoubleClick:
- WinForms
- Wpf
- Gtk
- Mac

Moved CellClick and CellDoubleClick from GridView to Grid

---

Source/Eto.WinForms/Forms/Controls/LinkButtonHandler.cs

Basically, a copy over from LabelHandler in WinForms that makes LinkButton behave similarly when Text property is set after it's been added to a layout.

* WinForms: Makes LinkButton text size behave similarly to Label

---

Source/Eto.Wpf/Forms/Controls/SplitterHandler.cs

fix #302
1. Method of choosing between Control.ActualWidth and Control.Width
(now based on `double.IsNaN` instead of `Control.IsLoaded`)
2. Adjustements for `FixedPanel = None` to behave correctly (visually checked against WinForms)
Note: AppVeyor failed due to XamMac.dll download failure
https://ci.appveyor.com/project/firda-cze/eto/build/2.1.0.1#L15
appveyor DownloadFile %XAMMAC_LOCATION%/XamMac.dll -FileName %BASE%\BuildOutput\net40\Release\XamMac.dll
Error downloading file: Could not find file 'C:\XamMac.dll'.
Command exited with code 2
Eto - Free.sln change (by VS) excluded, I cannot open Mac projects on Windows with VS2013 Community Edition.

Wpf Splitter.set_Position fix #302

---

Source/Eto.Wpf/Forms/ToolBar/ButtonToolItemHandler.cs

The grayed out function of a ToolButton doesn't only depends on the
Control.IsEnabled. It also needs the image to be disabled to show it.
Include source code style cleanups.

Fixes issue #334

---

Source/Eto/Forms/Menu/ButtonMenuItem.cs
Source/Eto/Forms/Menu/ContextMenu.cs
Source/Eto/Forms/Menu/MenuBar.cs
Source/Eto/Forms/ToolBar/ToolBar.cs

Only MenuBar has more content items like ApplicationItems, HelpItems, IncludeSystemItems which have to be in ```<ContentType.Items>...</ContentType.Items>``` format.
Do we really need them? Like HelpItems seems to be a shortcut do nothing es than creating a submenu for the help items. But this functionality can be created directly via the MenuItems.
```XML
<Dialog.MenuBar>
<MenuBar ID="MyMenubar">
...
<ButtonMenuItem ID="MyHelpItem" ToolTip="MyHelpItem">
<ButtonMenuItem ID="MyHelpItem1" ToolTip="MyHelpItem1" />
<ButtonMenuItem ID="MyHelpItem2" ToolTip="MyHelpItem1" />
<SeparatorMenuItem />
<ButtonMenuItem ID="MyHelpItem3" ToolTip="MyHelpItem3" />
</ButtonMenuItem>
</MenuBar>
</Dialog.MenuBar>
```
This shortcut has no platform impact itself (e.g. special show-up of the Help-Menu). But …

Fix for issue #336

---

Source/Eto.Gtk/Forms/Controls/SplitterHandler.cs
Source/Eto.Mac/Forms/Controls/SplitterHandler.cs
Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/Eto.Test.csproj
Source/Eto.Test/Eto.Test/MainForm.cs
Source/Eto.Test/Eto.Test/Sections/Controls/SplitterSection.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/SplitterTests.cs
Source/Eto.Test/Eto.Test/UnitTests/TestUtils.cs
Source/Eto.WinForms/Forms/Controls/PanelHandler.cs
Source/Eto.WinForms/Forms/Controls/SplitterHandler.cs
Source/Eto.Wpf/Forms/Controls/SplitterHandler.cs
Source/Eto.Wpf/Forms/WpfWindow.cs
Source/Eto/Eto - pcl.csproj
Source/Eto/Eto.csproj
Source/Eto/Forms/Controls/Splitter.cs
Source/Eto/Forms/ThemedControls/ThemedSplitterHandler.cs

replaces #311 and #310, fixes #309; Copy from #311:
*WinForms should be perfect - I am developing for WinForms for quite some time.
WPF looks good, but I still don't know all the corner-cases and am not sure about the events (will check later and possibly add more unit tests).
GTK2 should work fine, it is mostly based on WinForms implementation. GTK3 has different sizing mechanism, so, I guessed it (cannot curretnly test, but I will probably create some Linux VM in near future). SplitterWidth is guessed as well. I am not so familiar with GTK.*
***There is a stub for Mac, that should not break existing code, but new features are up to you.***
*ThemedSplitter is unfinished, tested under WinForms/D2D, but is not auto-sizing.*

Splitter.RelativePosition

---

Source/Eto.Gtk/Forms/ApplicationHandler.cs
Source/Eto.WinForms/Forms/ApplicationHandler.cs
Source/Eto.Wpf/Forms/ApplicationHandler.cs
Source/Eto/Eto - pcl.csproj
Source/Eto/Forms/Application.cs
Source/Eto/UnhandledExceptionEventHandler.cs

This change allows to catch otherwise unhandled exceptions.
Currently this is implemented for GTK, WinForms and WPF.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/picoe/eto/473)

Implement unhandled exceptions

---

Source/Eto.Mac/Forms/ApplicationHandler.cs
Source/Eto.Mac/Forms/Controls/WebViewHandler.cs

Two commits:
1. Adding back constructor for `ApplicationHandler` on Mac. Without this constructor, WebView on Mac doesn't redraw itself properly when rendering HTML/CSS with fixed positioned elements.
2. It turns out when overriding `UIRunOpenPanelForFileButton` method in WebView on Xamarin.Mac, `resultListener` argument will never be `WebOpenPanelResultListener` type therefore file upload function in WebView will be broken. Xamarin.Mac has new helper method which should be used instead and it fixes the issue with file upload.

Mac: Fix WebView redrawing and file upload issue

---

Source/Eto.Gtk/Forms/OpenFileDialog.cs
Source/Eto.Gtk/Forms/SaveFileDialog.cs
Source/Eto.Gtk/Forms/SelectFolderDialogHandler.cs

If this property is not set all the buttons will look the same. You can see the difference with Gtk buttons on the image bellow:
(https://developer.gnome.org/gtk3/stable/colorchooser.png)

Set default button for file dialogs

---

Source/Eto.Gtk/Forms/ColorDialogHandler.cs
Source/Eto.Gtk/NativeMethods.cs

The old GtkColorSelection has been depricated in 3.4 and replaced by GtkColorChooser. This implements the new one and uses it in case of Gtk 3.4 or newer.
GtkColorSelection: https://developer.gnome.org/gtk3/stable/GtkColorSelectionDialog.html
GtkColorChooser: https://developer.gnome.org/gtk3/stable/GtkColorChooserDialog.html

[GTK3] Implement New Color Chooser Dialog

---

Source/Eto/Forms/Menu/RadioMenuItem.cs

The error was happening because you were trying to connect events before creating the main object.

Fix RadioCommand NullException when using with Menu

---

Source/Eto.Gtk/Forms/Menu/ButtonMenuItemHandler.cs

The bug where submenu of contextmenu items were not firing activated signal was fixed in some recent release of Gtk 3 (the bug didn't exist in Gtk 2 afaik). This will also fix Ubuntu Unity menu not firing events, it didn't register ButtonPress and ButtonRelease events.

Remove workaround for ButtonMenuItem Activated event

---

Source/Eto.Gtk/Drawing/SystemColorsHandler.cs

gtk3 text view uses the wrong default text color, gtk entry is correct.

---

Source/Eto.Test/Eto.Test/UnitTests/Forms/Layout/StackLayoutTests.cs
Source/Eto/Forms/Container.cs
Source/Eto/Forms/Layout/TableCell.cs
Source/Eto/Forms/Layout/TableLayout.cs

- Also detach a control when it is removed from the logical parent, so that when you remove items from StackLayout/etc it will remove it from the visual tree immediately.

Fix removing controls from a TableLayout

---

Source/Eto.Direct2D/Drawing/ImageHandler.cs
Source/Eto.Gtk/Drawing/BitmapHandler.cs
Source/Eto.Mac/Drawing/BitmapHandler.cs
Source/Eto.Test/Eto.Test/UnitTests/Drawing/BitmapTests.cs
Source/Eto.Wpf/Drawing/BitmapHandler.cs

I've been toying with the as-yet-unofficial OpenGL control you, Phil Stopford and the SharpFlame devs have been working on, and in the process of dealing with texture loading I was led to a small bug in Eto's Bitmap class:
In Gtk2, when calling GetPixel on a 24bpp Bitmap without explicitly using Lock, the returned color has its red and blue components swapped. Conversely, calling Lock and using the version of GetPixel provided by the returned BitmapData works as expected.
Comparing the two functions, I think I see why [the BitmapData method](https://github.com/picoe/Eto/blob/develop/Source/Shared/BaseBitmapData.cs#L41) works, while [the BitmapHandler version](https://github.com/picoe/Eto/blob/develop/Source/Eto.Gtk/Drawing/BitmapHandler.cs#L250) is broken, with the latter assuming BGR …

Fix calling GetPixel on 24bpp bitmaps in Gtk2

---

Source/Eto.Test/Eto.Test/UnitTests/Drawing/BitmapTests.cs
Source/Eto.Test/Eto.Test/UnitTests/TestBase.cs
Source/Eto.Wpf/Drawing/BitmapHandler.cs
Source/Eto.Wpf/Drawing/GraphicsHandler.cs

Also added tests to ensure bitmaps can be created/updated from multiple threads using Graphics and/or Lock()
Fixes #485

Wpf: Fix creating/manipulating Bitmap objects from multiple threads

---

Source/Eto.Gtk/Forms/MessageBoxHandler.cs
Source/Eto.Gtk/GtkConversions.cs

The standard order for Gtk YesNoCancel dialog should be "No|Cancel|Yes", the current one was "No|Yes|Cancel". This type of dialog is easily seen in Gedit.

[Gtk] Fix button order for YesNoCancel dialog

---

Source/Eto.Gtk/Eto.Gtk2 - net45.csproj
Source/Eto.Gtk/Eto.Gtk2.csproj
Source/Eto.Gtk/Eto.Gtk3 - net45.csproj
Source/Eto.Gtk/Eto.Gtk3.csproj
Source/Eto.NativeGtk/Eto.NativeGtk - net45.csproj
Source/Eto.NativeGtk/Eto.NativeGtk.csproj
Source/Eto.Test/Eto.Test.Gtk2/Eto.Test.Gtk2 - net45.csproj
Source/Eto.Test/Eto.Test.Gtk3/Eto.Test.Gtk3 - net45.csproj
Source/Eto.Test/Eto.Test.Gtk3/Eto.Test.Gtk3.csproj
Source/Eto.Test/Eto.Test.NativeGtk/Eto.Test.NativeGtk - net45.csproj
Source/Eto.Test/Eto.Test.NativeGtk/Eto.Test.NativeGtk.csproj
appveyor.yml

Make all Gtk3/NativeGtk project files consistent with other project files, and remove code analysis and other superfluous elements.

Fix up Gtk3 warnings

---

Source/Eto.Gtk/Forms/Controls/DropDownHandler.cs

This PR allows for the combobox to be lower width than it's longest item. In case the item cannot fit in the combobox it will have "..." at the end.

[Gtk] Allow combobox to be lower size than it's longest item

---

Source/Eto.Gtk/Forms/Controls/SplitterHandler.cs

This sets the `shrink` param to `false`. What does it do? When set to `false` splitter will not allow to be moved bellow the minimum size. When set to `true` it will allow to be moved bellow the minimum size, but when that happens it will not resize the widgets inside it but will instead move the widgets outside of the target window.

[Gtk] Don't shrink splitter bellow allowed size

---

Source/Shared/EmbeddedAssemblyLoader.cs

Protects against poorly written code that handles AppDomain.ResourceResolve without first looking at the RequestingAssembly.  If the ResourceResolve attempts to load a non-existent assembly, it would cause a stack overflow.

Prevent possible stack overflow with EmbeddedAssemblyLoader

---

Source/Eto.Test/Eto.Test/UnitTests/Drawing/BitmapTests.cs
Source/Eto/Drawing/BitmapData.cs

Since the behaviour is undefined, we throw an exception to ensure unintended functionality isn’t relied upon.

Protect against calling Bitmap.Lock() more than once when there is still an open lock

---

Source/Eto.Gtk/Forms/Printing/PrintSettingsHandler.cs
Source/Eto.Gtk/GtkConversions.cs
Source/Eto.Gtk/NativeMethods.cs

Some genius decided to change the existing API to return an array of Gtk.PageRange objects instead of a single instance. We now use the native method directly to overcome differences in gtk# versions.

Gtk2/3: Fix getting page ranges from PrintSettings

---

Source/Eto.Gtk/Drawing/GraphicsHandler.cs
Source/Eto.Test/Eto.Test/UnitTests/Drawing/BitmapTests.cs
Source/Eto.Wpf/Drawing/BitmapHandler.cs
Source/Eto/Drawing/Bitmap.cs
Source/Eto/Drawing/BitmapData.cs

Wpf: Fix getting/setting pixels using Lock() with odd width, which would give it a stride larger than the pixels multiplied by bytes per pixel. Fixes #558
Properly throw the InvalidOperationException when trying to call BitmapData.Lock() more than once, before we get to the handler so it doesn’t put the bitmap in an invalid state.

Fixes for Bitmap.Lock()

---

Source/Eto.Mac/CrashReporter.cs
Source/Eto.Mac/Eto.Mac - net45.csproj
Source/Eto.Mac/Eto.Mac64 - net45.csproj
Source/Eto.Mac/Eto.XamMac - net45.csproj
Source/Eto.Mac/Eto.XamMac2 - mobile.csproj
Source/Eto.Mac/Eto.XamMac2 - net45.csproj
Source/Eto.Mac/Forms/ApplicationHandler.cs
Source/Eto.Test/Eto.Test/MainForm.cs

- Causes macOS to generate a crash report in Console, and includes the .NET stack trace.

Mac: Use CrashReporter when an unhandled exception occurs.

---

Source/Eto.Gtk/Forms/Controls/TextBoxHandler.cs
Source/Eto.Gtk/Forms/Controls/TextStepperHandler.cs
Source/Eto.Mac/Forms/Controls/MacText.cs
Source/Eto.Mac/Forms/Controls/StepperHandler.cs
Source/Eto.Mac/Forms/Controls/TextBoxHandler.cs
Source/Eto.Test/Eto.Test/Sections/Controls/TextBoxSection.cs
Source/Eto.Test/Eto.Test/Sections/Controls/TextStepperSection.cs
Source/Eto.Test/Eto.Test/UnitTests/Handlers/Controls/TestTextBoxHandler.cs
Source/Eto.WinForms/Forms/Controls/TextBoxHandler.cs
Source/Eto.WinForms/Forms/Controls/TextStepperHandler.cs
Source/Eto.WinRT/Forms/Controls/TextBoxHandler.cs
Source/Eto.Wpf/Forms/Controls/TextBoxHandler.cs
Source/Eto.Wpf/Forms/Controls/TextStepperHandler.cs
Source/Eto.Wpf/WpfConversions.cs
Source/Eto.iOS/Forms/Controls/SearchBoxHandler.cs
Source/Eto.iOS/Forms/Controls/TextBoxHandler.cs
Source/Eto/Forms/Controls/TextBox.cs
Source/Eto/Forms/Controls/TextStepper.cs
Source/Eto/Forms/ThemedControls/ThemedTextStepperHandler.cs

- Gtk: TextStepper now uses default behaviour of responding to up/down keystrokes
- TextBox.MaxLength now normalized across platforms.  0 = unlimited, which is now default. -1 will throw an exception.
- TextBox.ShowBorder now works correctly on all platforms

Add TextBox.TextAlignment and TextStepper.ShowStepper.

---

Source/Eto.Test/Eto.Test.Gtk2/Eto.Test.Gtk2 - net45.csproj

- Gtk for .NET installer on windows packages Mono.Cairo 4.0, but gtk-sharp, etc all reference Mono.Cairo 2.0.

Fix Gtk2 build warning on windows

---

Source/Eto.Wpf/Forms/Controls/SplitterHandler.cs
Source/Eto.Wpf/Forms/WpfFrameworkElement.cs

- Fix setting new panel content with splitter if previous control was not visible
- Fix Control.Visible to use the ContainerControl to set visibility, which is only different on certain controls (e.g. TableLayout)
- Fix setting visibility of a panel before it is loaded
Fixes #644

Wpf Splitter fixes

---

Source/Eto.Test/Eto.Test/Sections/Controls/SplitterSection.cs
Source/Eto.WinForms/Forms/Controls/SplitterHandler.cs
Source/Eto/Forms/Binding/BindableWidget.cs

- Test when replacing Panel1 or Panel2 with a new control with different visibility, or null.
- WinForms: Fix setting Panel1/Panel2 to new control when its initial Visible state is set.
- Fix Unbind() by removing the item from Properties, instead of setting the value to null.

Add additional tests for Splitter hiding

---

Source/Eto.Gtk/Forms/ClipboardHandler.cs

Second parameter (data type) is number of bits per unit 8 = byte.
Fixes #651

Gtk: Fix Clipboard.SetData()

---

Source/Eto.Android/Forms/AndroidControl.cs
Source/Eto.Direct2D/Drawing/GraphicsHandler.cs
Source/Eto.Direct2D/Forms/Controls/DrawableHandler.cs
Source/Eto.Gtk/Forms/Controls/TextBoxHandler.cs
Source/Eto.Gtk/Forms/GtkControl.cs
Source/Eto.Mac/Forms/Controls/DrawableHandler.cs
Source/Eto.Mac/Forms/MacContainer.cs
Source/Eto.Mac/Forms/MacView.cs
Source/Eto.Test/Eto.Test/UnitTests/Handlers/Controls/TestControlHandler.cs
Source/Eto.Test/Eto.Test/UnitTests/Handlers/Controls/TestDrawableHandler.cs
Source/Eto.WinForms/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.WinForms/Forms/HwndFormHandler.cs
Source/Eto.WinForms/Forms/WindowsControl.cs
Source/Eto.WinRT/Forms/Controls/DrawableHandler.cs
Source/Eto.WinRT/Forms/Controls/ScrollableHandler.cs
Source/Eto.WinRT/Forms/WpfContainer.cs
Source/Eto.WinRT/Forms/WpfFrameworkElement.cs
Source/Eto.Wpf/Forms/Controls/DrawableHandler.cs
Source/Eto.Wpf/Forms/Controls/GridHandler.cs
Source/Eto.Wpf/Forms/Controls/ScrollableHandler.cs
Source/Eto.Wpf/Forms/WpfContainer.cs
Source/Eto.Wpf/Forms/WpfFrameworkElement.cs
Source/Eto.iOS/Forms/IosView.cs
Source/Eto/Forms/Controls/Control.cs
Source/Eto/Forms/Controls/ThemedControlHandler.cs

- By default, all children are invalidated which can be overly CPU intensive.  Passing false will only invalidate the immediate control/container for cases where that is necessary.

Add invalidateChildren parameter to Control.Invalidate()

---

Source/Eto.WinForms/Forms/Controls/TextAreaHandler.cs
Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs

Wpf: set language to the current input language, otherwise setting the selection attributes does not work when inserting text
Wpf: Use the document page padding instead of magic numbers when wrap is false, and get the ceiling of the width so it doesn’t wrap text incorrectly.
WinForms: Use DualFont language options so entering in different input languages works.

RichTextArea multilingual updates

---

Source/Eto.Gtk/Forms/Controls/ScrollableHandler.cs

ScrollEvent is not actually a scroll event for ScrolledWindow in Gtk :) It's a general purpose check if mouse wheel moved.

[Gtk] Fix scrollable scroll event

---

Source/Eto.Test/Eto.Test/Sections/Controls/RichTextAreaSection.cs
Source/Eto.Wpf/Drawing/FontHandler.cs
Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs

Wpf: RichTextArea.SelectionFont now returns correct font size in high dpi.
Wpf: Use TextFormattingMode of document to calculate width when wrap is false
Wpf: Optimize getting width of text by reducing allocations for lambda

More RichTextArea updates

---

Source/Eto.Mac/Forms/MacFileDialog.cs
Source/Eto.Mac/Forms/SelectFolderDialogHandler.cs
Source/Eto/Forms/ThemedControls/ThemedFontPickerHandler.cs

- FilePicker crashes on macOS as the Folder/FileDialog.Title is set to null
- ThemedFontPickerHandler should allow for a modeless dialog by using the FontChanged event instead of the return value of ShowDialog().
- SelectFolderDialog will return the selected folder, not just the enclosing folder

Mac: Fix FontPicker and FilePicker

---

Source/Eto.Wpf/Forms/Controls/TabControlHandler.cs

Fixes Splitter > Dynamic splitter creation test.

Wpf: Fix setting scale of a tab control when inserted at runtime.

---

Source/Eto.Gtk/Forms/Controls/GridHandler.cs
Source/Eto.Gtk/Forms/Controls/GtkTreeModel.cs
Source/Eto.Gtk/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.Gtk/Forms/GtkControl.cs
Source/Eto.Gtk/GtkConversions.cs
Source/Eto.Mac/Forms/Controls/GridHandler.cs
Source/Eto.Mac/Forms/Controls/GridViewHandler.cs
Source/Eto.Mac/Forms/Controls/ScrollableHandler.cs
Source/Eto.Mac/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.Mac/MacConversions.cs
Source/Eto.Test/Eto.Test/Sections/Controls/GridViewSection.cs
Source/Eto.Test/Eto.Test/Sections/Controls/TreeGridViewSection.cs
Source/Eto.Test/Eto.Test/UnitTests/Handlers/Controls/TestGridViewHandler.cs
Source/Eto.WinForms/CustomControls/TreeController.cs
Source/Eto.WinForms/Forms/Controls/GridHandler.cs
Source/Eto.WinForms/Forms/Controls/ScrollableHandler.cs
Source/Eto.WinForms/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.WinForms/WinConversions.cs
Source/Eto.Wpf/Forms/Controls/GridHandler.cs
Source/Eto.Wpf/Forms/Controls/ScrollableHandler.cs
Source/Eto.Wpf/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.Wpf/WpfConversions.cs
Source/Eto/Forms/Controls/Grid.cs
Source/Eto/Forms/Controls/TreeGridView.cs

This is a work in progress, and will hopefully fix a ton of issues with the TreeGridView.  Not full MVVM yet, but one step closer to getting that implemented.
It adds some apis:
- `TreeGridView.GetCellAt(PointF location)` - get the column & item at a specified point
- `TreeGridView.ReloadData()` - reload all data, keeping selection
- `TreeGridView.ReloadItem(ITreeGridItem item)` - reload the specified item and its children (helps with #493, but still not a full fix yet)
- `Grid.Border` - specify the type of border, or none (similar to Scrollable)
Fixes some things:
- Make mouse up/down events consistent and usable, combined with `GetCellAt()` should be very useful
- Fix `TreeGridView.SelectedItems` when allowing multiple selection (#451)
- Performance issues on some platforms
- Expanding …

TreeGridView updates

---

Source/Eto.Gtk/Forms/Controls/SplitterHandler.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/SplitterTests.cs

- Add SplitterHandler.ShrinkContentsToFit property so you can get the new functionality with a style.
- Gtk3 will retain the new functionality as it doesn’t crash.
- Fix leak when recreating the paned control by unhooking the Realized event

Gtk2: fix gtk splitter to work the old way as it’s causing too many crashes with Eto.Test.

---

Source/Eto.Gtk/Forms/Controls/GtkTreeModel.cs
Source/Eto.Gtk/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.Mac/Forms/Controls/MacImageAndTextCell.cs
Source/Eto.Test/Eto.Test/Sections/Controls/TreeGridViewSection.cs
Source/Eto.WinForms/Forms/Controls/TreeGridViewHandler.cs

- Gtk: When removing all children from an expanded row it would get into an invalid state. Fixes #681
- Gtk: Properly expand child items when a node is expanded.
- Mac: Fix showing text in ImageTextCell when image is larger than the row height.
- WinForms: Fix keeping (proper) selection when refreshing and some crashing bugs.
- TreeGridViewSection now tests removing multiple children when enabled.

Fix some TreeGridView bugs:

---

Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/PanelTests.cs
Source/Eto/Forms/Container.cs
Source/Eto/Widget.cs

- Removing the content of a Panel didn’t unset the LogicalParent properly if it was the current container.
- Add ID to the ToString() of a Widget to more easily debug things.
- Simplify logic of SetParent() slightly, as Detatch() will take care of checking a few things.
- Add tests
Fixes #682

Fix setting Parent of Panel.Content

---

Source/Eto.Mac/Forms/Controls/SplitterHandler.cs

This ensures if it’s set to a control with Visible = false, or null, then it will collapse the splitter.
Fixes #500

Mac: Update Splitter position when a panel is replaced.

---

Source/Eto.Gtk/Forms/Controls/GridHandler.cs
Source/Eto.Gtk/Forms/GtkControl.cs

In short, Gtk default treeview multiselect is extremely broken since right click does the same things as left click so you actually need a bit of code to make it act like the VisualStudio/XamarinStudio/MonoDevelop solution explorer treeview acts.

[Gtk] Fix TreeGridView Multiselect

---

Source/Eto.Test/Eto.Test/UnitTests/Forms/Layout/StackLayoutTests.cs
Source/Eto.Test/Eto.Test/UnitTests/TestBase.cs
Source/Eto/Forms/Layout/StackLayout.cs
Source/Eto/Forms/RelayCommand.cs

- No longer update StackLayoutItem alignment after aligning the label so it remains the same value.
- Added manual test for StackLayout to reproduce the issue.
- Added TestBase.ManualForm with pass/fail buttons to make it easier to create more manual tests.
- Also added non-generic RelayCommand which I’ve been meaning to add for a while to make it easier to create a command that does not need a parameter.

Fix label alignment in StackLayout when it is recreated.

---

Source/Eto.Wpf/Forms/WpfWindow.cs

No other platform shows them, so WPF shouldn't either.

[WPF] Hide resize grip

---

Source/Eto.Gtk/Forms/GtkWindow.cs

Notes:
- Setting Min and Max Size to the same value does remove resizable from the border
- I had to use `9999999` because contrary to the documentation `-1` does not work

[Gtk] Fix Window Resizable param

---

Source/Eto.Test/Eto.Test/Sections/Behaviors/ScreenSection.cs
Source/Eto.WinForms/Win32.cs
Source/Eto.WinForms/Win32.dpi.cs
Source/Eto.Wpf/Forms/MouseHandler.cs
Source/Eto.Wpf/Forms/PerMonitorDpiHelper.cs
Source/Eto.Wpf/Forms/ScreenHandler.cs
Source/Eto.Wpf/Forms/WpfFrameworkElement.cs
Source/Eto.Wpf/Forms/WpfWindow.cs
Source/Eto.Wpf/WpfExtensions.cs
Source/Eto/Forms/Layout/DynamicLayout.cs

WPF Does not report correct window location when using per-monitor DPI settings, as they are transformed by the current screen DPI.  E.g. with 100% left monitor, 200% right monitor, when you move the window from the left to the right, the location becomes incorrect.
- Use Win32 methods to get/set location of windows
- Mouse.Position is now in logical co-ordinates
- Control.PointTo/FromScreen now expect logical co-ordinates
- Add DynamicLayout.BeginCentered/EndCentered

Wpf: Change screen/mouse position to logical coordinates.

---

Source/Eto.Mac/Eto.XamMac2 - mobile.csproj
Source/Eto.Mac/Forms/Controls/SpinnerHandler.cs
Source/Eto.Mac/Forms/DialogHandler.cs
Source/Eto.Mac/Forms/MacModal.cs
Source/Eto.Mac/Forms/MacView.cs
Source/Eto.Mac/Forms/MacWindow.cs
Source/Eto.Mac/Messaging.cs
Source/Eto.Test/Eto.Test/Sections/Controls/KitchenSinkSection.cs
Source/Eto.Test/Eto.Test/Sections/Dialogs/DialogSection.cs
Source/Eto/Forms/Layout/DynamicLayout.cs

Apparently, the use of NSWindow.ParentWindow is an incorrect way to set the parent of a dialog.  The only way it seems is to use a sheet, otherwise the Dialog will always be application modal instead of modal only to the owner window.
- Mac: Fix setting the BackgroundColor on a container control where the children would stretch instead of redraw when the container is resized.
- Mac: Fix Spinner to autosize to the minimum of the width/height instead of the maximum so it’ll fit properly
- Add DynamicLayout.AddSeparateColumn() helper (same concept as AddSeparateRow())
- Update KitchenSinkSection to add some of the newer controls
- Update DialogSection test to add more options and apply them to the KitchenSink dialog as well.

Mac: Fix setting owner of a Dialog, etc.

---

Source/Eto.Gtk/Forms/TableLayoutHandler.cs
Source/Eto.Test/Eto.Test/Sections/Behaviors/AllControlsBase.cs
Source/Eto/Forms/Application.cs

Register Application.UnhandledExceptionEvent properly to handle subclass overrides
Fixes #728

Gtk: Fix mouse events with TableLayout.

---

Source/Eto.Test/Eto.Test/Sections/Drawing/ClearSection.cs
Source/Eto.Wpf/Drawing/GraphicsHandler.cs

If modifying the same image multiple times it wouldn’t update the image properly.
Fixes #702

Wpf: Fix Graphics.Clear() on a Bitmap

---

Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/Sections/Drawing/AntialiasSection.cs
Source/Eto.Test/Eto.Test/UnitTests/Drawing/BitmapTests.cs
Source/Eto.Test/Eto.Test/UnitTests/Drawing/BrushTests.cs
Source/Eto.Test/Eto.Test/UnitTests/Drawing/FontTests.cs
Source/Eto.Test/Eto.Test/UnitTests/Drawing/GraphicsTests.cs
Source/Eto.Wpf/Drawing/BitmapHandler.cs
Source/Eto.Wpf/Drawing/FontHandler.cs
Source/Eto.Wpf/Drawing/GraphicsHandler.cs
Source/Eto.Wpf/Drawing/LinearGradientBrushHandler.cs
Source/Eto.Wpf/Drawing/RadialGradientBrushHandler.cs
Source/Eto.Wpf/Drawing/SolidBrushHandler.cs
Source/Eto.Wpf/Drawing/TextureBrushHandler.cs
Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
Source/Eto.Wpf/WpfConversions.cs

- Wpf: Also fix turning on/off Graphics.AntiAlias and add unit test
- Add unit tests for font and brushes when used from other threads.
Fixes #645

Wpf: Fix using brushes and fonts created from other threads

---

Source/Eto.Wpf/Forms/Controls/ProgressBarHandler.cs
Source/Eto/Forms/Layout/StackLayout.cs

- Wpf: Prevent using a ProgressBar from flooding message loop when IsIndeterminate = true and no longer used.
- StackLayout: Don’t return null in Controls enumeration, prevents unbinding

Wpf: ProgressBar fix when embedded in win32 app.

---

Source/Eto.Test/Eto.Test/Sections/Controls/GridViewSection.cs
Source/Eto.Test/Eto.Test/Sections/Controls/TreeGridViewSection.cs
Source/Eto.Wpf/Forms/Cells/CheckBoxCellHandler.cs
Source/Eto.Wpf/Forms/Cells/ComboBoxCellHandler.cs
Source/Eto.Wpf/Forms/Cells/CustomCellHandler.cs
Source/Eto.Wpf/Forms/Cells/DrawableCellHandler.cs
Source/Eto.Wpf/Forms/Controls/StepperHandler.cs
Source/Eto.Wpf/WpfExtensions.cs

- CheckBoxCell triggered change events while scrolling if a previous row was checked/unchecked
- ComboBoxCell did not apply formatting when initially displayed
- CustomCell and Drawable did not change data context properly when scrolling
- Fix possible crash in Stepper

Wpf: Fix some bugs in GridView/TreeGridView

---

Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/Sections/Behaviors/AllControlsBase.cs
Source/Eto.Test/Eto.Test/Sections/Controls/MaskedTextStepperSection.cs
Source/Eto.Wpf/Forms/Controls/ComboBoxHandler.cs
Source/Eto.Wpf/Forms/Controls/DropDownHandler.cs
Source/Eto.Wpf/Forms/Controls/TextStepperHandler.cs
Source/Eto/Eto - pcl.csproj
Source/Eto/Forms/Controls/MaskedTextStepper.cs
Source/Eto/Forms/Controls/ThemedControlHandler.cs
Source/Eto/Forms/ThemedControls/ThemedTextStepperHandler.cs

Wpf: Fix setting TextStepper.BackgroundColor and TextColor
Wpf: Fix ComboBox.BackgroundColor to fill entire combo box not just text area
Mac: Fix setting BackgroundColor for ThemedTextStepperHandler
Add MaskedTextStepper and NumericMaskedTextStepper

TextStepper fixes

---

Source/Eto.Test/Eto.Test/Sections/Behaviors/FocusEventsSection.cs
Source/Eto.Wpf/Forms/Controls/TextBoxHandler.cs
Source/Eto.Wpf/Forms/Controls/TextStepperHandler.cs
Source/Eto.Wpf/Forms/WpfFrameworkElement.cs
appveyor.yml

- GotFocus/LostFocus would fire many times for most controls, even when it didn’t lose focus
- TextStepper should not allow keyboard focus to the spin buttons to have similar behaviour to NumericStepper.
- Show HasFocus property in the FocusEventsSection test.

Wpf: Fix focus events

---

Source/Eto/Forms/Controls/MaskedTextBox.cs
Source/Eto/Forms/Controls/MaskedTextStepper.cs

Useful when creating subclasses that may have different states of the control or react to other events and properties.

Make MaskedTextBox/Stepper’s UpdateText method protected virtual.

---

Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/Sections/UnitTestSection.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/ControlEventTests.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/RichTextAreaTests.cs
Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
Source/Eto/Forms/Controls/RichTextArea.cs

When loading RTF for example and the cursor is over underlined text, it will sometimes not show the correct value for these properties as there’s nefarious empty decoration collections in the document.
- Added RichTextArea.Rtf helper property
- Add ITextBuffer.GetRtf() and SetRtf() helper extension methods
- Added unit tests

Wpf: Fix RichTextArea.SelectionUnderline and SelectionStrikethrough in some cases.

---

Source/Eto.Mac/Drawing/GraphicsHandler.cs

it is part of the graphics state so it would be wiped out whenever we changed transform, etc.

Mac: Fix Graphics.AntiAlias

---

Source/Eto.Mac/Forms/Controls/SplitterHandler.cs

For example, the AnchorSection would mess up the splitter when resizing the window.

Mac: Fix resizing a Splitter when code updates the layout during the resize.

---

Source/Eto.Mac/Forms/Controls/GridHandler.cs
Source/Eto.Mac/Forms/Controls/TextAreaHandler.cs
Source/Eto.Test/Eto.Test.Mac/Eto.Test.Mac - net45.csproj
Source/Eto.Test/Eto.Test.Mac/Eto.Test.Mac64 - net45.csproj
Source/Eto.Test/Eto.Test.Mac/Eto.Test.XamMac - net45.csproj
Source/Eto.Test/Eto.Test.Mac/Eto.Test.XamMac2 - mobile.csproj
Source/Eto.Test/Eto.Test.Mac/Eto.Test.XamMac2 - net45.csproj
Source/Eto.Test/Eto.Test.Mac/UnitTests/RichTextAreaHandlerTests.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/RichTextAreaTests.cs

Fixes setting TextArea.Enabled to false then back to true.  It would leave ReadOnly set to true even though it was not set.
Also fixes minor issue with Grid.SelectedRows to allow it to be set to null.

Mac: Fix TextArea.Enabled

---

Source/Eto.Mac/Forms/MacWindow.cs

This is when using non-Eto code that utilizes MonoMac/Xamarin.Mac.  In this case, the menu wouldn't be restored when an Eto form loses focus.  Now it saves the old menu, even if it's from Eto and restores it when a window loses focus.  It will also properly save the old menu if you set a window's menu after it is shown.

Mac: Restore menu regardless of if it has a monomac/xammac instance or not

---

Source/Eto.Mac/Forms/Controls/PanelHandler.cs
Source/Eto.Mac/Forms/Controls/ScrollableHandler.cs
Source/Eto.Mac/Forms/MacBase.cs
Source/Eto.Mac/Forms/MacObject.cs
Source/Eto.Mac/Forms/MacView.cs
Source/Eto.Mac/Messaging.cs
Source/Eto.Mac/ObjCExtensions.cs
Source/Eto.Test/Eto.Test.Mac/Eto.Test.Mac - net45.csproj
Source/Eto.Test/Eto.Test.Mac/UnitTests/ScrollableTests.cs
Source/Eto.Test/Eto.Test/Sections/Controls/ControlColorsSection.cs

When using a background color (which required a layer), we used CanDrawSubviewsIntoLayer to collapse layers.  This unfortunately made the Scrollable draw its content on the containing layer initially when it was dynamically added to the form.
We no longer use layers to draw the background color - we add the drawRect: method to the ContainerControl dynamically and draw it there.

Mac: Fix Scrollable when dynamically added to a container with a background color

---

Source/Eto.Test/Eto.Test/Handlers/TabPageHandler.cs
Source/Eto.Test/Eto.Test/Sections/Controls/ButtonSection.cs
Source/Eto.Test/Eto.Test/Sections/Controls/KitchenSinkSection.cs
Source/Eto.Test/Eto.Test/Sections/Controls/TabControlSection.cs
Source/Eto.Wpf/Forms/Controls/ButtonHandler.cs
Source/Eto.Wpf/Forms/Controls/LabelHandler.cs
Source/Eto.Wpf/Forms/Controls/TabPageHandler.cs
Source/Eto.Wpf/Forms/PerMonitorDpiHelper.cs
Source/Eto.Wpf/Forms/WpfFrameworkElement.cs

- TabPage now puts a margin between the image and text
- Window.LogicalPixelSize is now reported correctly when using built-in dpi handling
- Button now sizes correctly when adjusting its MinimumSize
- Remove old sizing code to set minimum size of controls as we now rely on Measure/Arrange overrides for all controls.

Wpf: TabPage and Dpi fixes

---

Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/ControlTests.cs
Source/Eto.Wpf/Forms/Controls/ComboBoxHandler.cs
Source/Eto.Wpf/Forms/Controls/ProgressBarHandler.cs
Source/Eto.Wpf/Forms/Controls/SliderHandler.cs
Source/Eto.Wpf/Forms/WpfFrameworkElement.cs

Wpf: Fix setting text before setting data store
Wpf: ProgressBar and Slider should have sane default sizes

Wpf: Fix regression when controls are set to their default size.

---

Source/Eto.Test/Eto.Test.Wpf/Eto.Test.Wpf - net45.csproj
Source/Eto.Test/Eto.Test.Wpf/UnitTests/ScrollableTests.cs
Source/Eto.Wpf/Forms/Controls/ScrollableHandler.cs

Problem:
Assigning a value to the Scrollable.ScrollSize property results in an error: 
> Unable to cast object of type 'EtoScrollViewer' to type 'System.Windows.Controls.Border'.
The bug is found in `Eto / Source / Eto.Wpf / Forms / Controls / ScrollableHandler.cs`, 
`public Size ScrollSize`, in the line 
`var content = (swc.Border) Control.Child;`
The exception is eliminated. I wanted to write a test, but unfortunately, my VS2015 + Resharper at work is buggy and does not want to work with NUnit. And at home the whole project Eto is not build to, I have not yet found why.

Fix for #480, #833 and test

---

Source/Eto.Mac/Forms/MacView.cs

Xamarin.Mac is more picky on the method signature, although it was incorrectly missing the '=' between the type and declaration.  It assumes it is there otherwise it goes out of bounds.
Fixes #848

XamMac: Fix regression when using BackgroundColor

---

Source/Eto.Wpf/Forms/Controls/GridViewHandler.cs

- In some scenarios the GridView would iterate through all elements to get an item at a particular index.
Fixes #811

Wpf: Fix slow GridView when bound to a non-generic list

---

Source/Eto.Mac/Forms/Controls/CheckBoxHandler.cs
Source/Eto.Mac/Forms/Controls/RadioButtonHandler.cs
Source/Eto.Test/Eto.Test.Wpf/Startup.cs
Source/Eto.Test/Eto.Test/Sections/Controls/CheckBoxSection.cs
Source/Eto.Test/Eto.Test/Sections/Controls/RadioButtonSection.cs
Source/Eto.Wpf/Forms/Controls/CheckBoxHandler.cs
Source/Eto.Wpf/Forms/Controls/RadioButtonHandler.cs

Mac/Wpf: Ensure RadioButton and CheckBox are vertically centered to text
Wpf: Grey out text for RadioButton/CheckBox when disabled.

RadioButton/CheckBox tweaks for Mac/WPF

---

Source/Eto.Gtk/KeyMap.cs
Source/Eto.Mac/KeyMap.cs
Source/Eto.WinForms/KeyMap.cs
Source/Eto.Wpf/KeyMap.cs
Source/Eto/Forms/Key.cs

- Map all keys possible
- Keys.Plus is deprecated for Equal (which was only mapped on Gtk and Mac before)
- Keys.ForwardSlash is deprecated for Slash
- Added Keypad0-9, Mulitply, Add, Subtract, Help, Pause, and Clear, and KeypadEqual keys
- Use macOS symbols when translating Keys to a shortcut string on a mac.

Add better support for more keys in all platforms.

---

Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/NumericStepperTests.cs
Source/Eto.Wpf/Forms/Controls/NumericStepperHandler.cs

WPF would keep the text the user entered, even though the actual value was changed.
Tests added to verify behaviour on all platforms.

Wpf: Fix setting value of NumericStepper during ValueChanged event

---

Source/Eto.Test/Eto.Test/UnitTests/Drawing/IconTests.cs
Source/Eto/Drawing/Icon.cs

When using Icon.FromResource with a .png, it will search for @2x, etc files.  When none are found you get an odd error instead of an ArgumentException.

Icon.FromResource should throw ArgumentException when no resources found.

---

Source/Eto.Gtk/Forms/Controls/DrawableHandler.cs
Source/Eto.Gtk/Forms/Controls/DropDownHandler.cs
Source/Eto.Gtk/Forms/GtkControl.cs
Source/Eto.Gtk/Forms/TableLayoutHandler.cs
Source/Eto.Mac/Forms/Controls/GridHandler.cs
Source/Eto.Mac/Forms/Controls/GridViewHandler.cs
Source/Eto.Mac/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.Mac/Forms/DialogHandler.cs
Source/Eto.Mac/Forms/FormHandler.cs
Source/Eto.Mac/Forms/MacControlExtensions.cs
Source/Eto.Mac/Forms/MacView.cs
Source/Eto.Mac/Forms/MacWindow.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/ControlEventTests.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/ControlTests.cs
Source/Eto.Test/Eto.Test/UnitTests/TestBase.cs
Source/Eto.WinForms/CustomControls/ExtendedDateTimePicker.cs
Source/Eto.WinForms/Forms/Controls/DropDownHandler.cs
Source/Eto.WinForms/Forms/Controls/TextBoxHandler.cs
Source/Eto.WinForms/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.WinForms/Forms/WindowsControl.cs
Source/Eto/Forms/Controls/Spinner.cs
Source/Eto/Forms/Controls/ThemedControlHandler.cs

- Gtk: Fix getting/setting properties/events before TableLayout is created (e.g. using Rows to construct)
- Mac: Fix autosizing columns when TreeGridView/GridView data is changed and visible rows are unchanged.
- WinForms: Fix TreeGridView.Activated event to only trigger when the Enter key is pressed (instead of any key)
- WinForms: TextBox should not select all when setting the selection or caret before it is shown

Implement Control.Shown event on all platforms

---

Source/Eto.Wpf/Forms/Cells/ImageTextCellHandler.cs
Source/Eto.Wpf/Forms/Cells/TextBoxCellHandler.cs

Sometimes you may wish the mouse in a TextBoxCell and ImageTextCell to only select text but not drag selected text.  This adds a property to the handlers so you can apply it with a style. E.g.
Style.Add<Eto.Wpf.Forms.Cells.TextBoxCellHandler>("no-mouse-drag", handler => handler.UseMouseSelectionOnly = true);
Style.Add<Eto.Wpf.Forms.Cells.ImageTextCellHandler>("no-mouse-drag", handler => handler.UseMouseSelectionOnly = true);

Wpf: This adds a UseMouseSelectionOnly property to TextBoxCell/ImageTextCell to use from a native style.

---

Source/Eto.Gtk/Forms/Controls/ImageViewHandler.cs
Source/Eto.Test/Eto.Test/Sections/Controls/ImageViewSection.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/ImageViewTests.cs
Source/Eto.WinForms/Drawing/BitmapHandler.cs
Source/Eto.WinForms/Forms/Controls/ImageViewHandler.cs
Source/Eto.Wpf/CustomControls/MultiSizeImage.cs
Source/Eto.Wpf/Drawing/IconHandler.cs
Source/Eto.Wpf/Forms/Controls/ImageViewHandler.cs

- When changing the image, the ImageView should auto size to the new image if no explicit size is set
- When setting to null, the size should be 0,0 (or 1,1 on Gtk & WinForms).
Wpf: Fix using a bitmap loaded from a separate thread in some cases
Wpf: Fix ImageView when size is reported as 0,0
WinForms: Fix ImageView when size is reported as 0,0. Fixes #876

ImageView updates for sizing when setting to different images

---

Source/Eto.Gtk/Forms/Controls/TextAreaHandler.cs
Source/Eto.Mac/Forms/Controls/RichTextAreaHandler.cs
Source/Eto.Mac/Forms/Controls/TextAreaHandler.cs
Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/RichTextAreaTests.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/Controls/TextAreaTests.cs
Source/Eto.WinForms/Forms/Controls/RichTextAreaHandler.cs
Source/Eto.WinForms/Forms/Controls/TextAreaHandler.cs
Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
Source/Eto.Wpf/Forms/Controls/TextAreaHandler.cs
Source/Eto/Forms/Controls/RichTextArea.cs
Source/Eto/Forms/Controls/TextControl.cs
Source/Eto/Forms/Range.cs
Source/Eto/PropertyStore.cs

Changing TextArea/RichTextArea Text property should set selection to end on all platforms.
Add Range.FromLength() and WithLength() helper methods for int-based ranges.
Wpf: Implement RichTextArea.CaretIndexChanged event

Setting RichTextArea.SelectedText should trigger TextChanged and SelectionChanged events

---

Source/Eto.Gtk/Forms/ClipboardHandler.cs
Source/Eto.Test/Eto.Test/Eto.Test - pcl.csproj
Source/Eto.Test/Eto.Test/Sections/Behaviors/ClipboardSection.cs
Source/Eto.Test/Eto.Test/UnitTests/Forms/ClipboardTests.cs
Source/Eto.WinForms/Forms/ClipboardHandler.cs
Source/Eto.Wpf/Forms/ClipboardHandler.cs

- Wpf: Can now specify more than one type in the clipboard by setting various properties.
- Wpf: Added protection when getting the value and retries 10 times after 100ms delay as some times it throws a com exception that it cannot open the clipboard.
- Gtk: Fix up Clipboard.Image so it doesn't wipe all other values in the clipboard
- Gtk: Setting Clipboard.Text sets all text variants, not just utf8.
- Gtk: Getting/Setting Clipboard.Html now works correctly
- Added unit tests to verify behaviour

Fix up Clipboard on all platforms to behave similarly.

---

Source/Eto.Mac/Forms/Controls/ListBoxHandler.cs
Source/Eto.Mac/Forms/MacView.cs

When an NSScrollView is set to 0,0 size, it shouldn't give constraint warnings.  The warnings were due to using a border which requires at least a 2,2 size so we turn off the border if it's smaller than 2,2 and restore if it gets bigger.

Mac: Fix constraint warnings when using an NSScrollView

---

Source/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs

Can be overridden using a native wpf style using the RichTextAreaHandler.AllowImages property

Wpf: Disable pasting of images into RichTextArea by default

---

Source/Eto.WinForms/Eto.WinForms - net45.csproj
Source/Eto.WinForms/KeyMap.cs
Source/Eto.WinForms/WinConversions.cs
Source/Eto.WinForms/WinConversions.shared.cs
Source/Eto.Wpf/Eto.Wpf - net45.csproj
Source/Eto.Wpf/Forms/WindowsFormsHostHandler.cs

WindowsFormsHostHandler can be used to wire up windows forms controls easier while routing all mouse & keyboard events properly.

Wpf: Add WindowsFormsHostHandler

---

Source/Eto.Mac/Forms/Controls/MacLabel.cs
Source/Eto.Mac/Forms/DialogHandler.cs

Fixes label sizing when wrapping is on and is resized.
Also removes the 2px spacing at the bottom of a Dialog when there are no buttons present and ensures the content doesn't overlap the spacing.

Mac: Label and Dialog fixes

---

Source/Eto.Gtk/Forms/GtkControl.cs
Source/Eto.Gtk/NativeMethods.cs
Source/Eto.Gtk/NativeMethods.tt
Source/Eto.Mac/Forms/Controls/GridViewHandler.cs
Source/Eto.Mac/Forms/Controls/TreeGridViewHandler.cs
Source/Eto.Test/Eto.Test/Sections/Behaviors/DragDropSection.cs
Source/Eto.Wpf/Forms/WpfFrameworkElement.cs

Wpf: Fix constant flashing of drag cursor for TreeGridView/GridView. Fixes #932
Gtk: Clear out old DragArgs so one operation doesn't affect another
Mac: Fix setting indicator for GridView in some cases

Drag 'n Drop fixes

---

build/nuspec/Eto.Platform.Direct2D.nuspec
build/nuspec/Eto.Platform.Gtk.nuspec
build/nuspec/Eto.Platform.Gtk3.nuspec
build/nuspec/Eto.Platform.Mac.nuspec
build/nuspec/Eto.Platform.Mac64.nuspec
build/nuspec/Eto.Platform.WinRT.nuspec
build/nuspec/Eto.Platform.Windows.nuspec
build/nuspec/Eto.Platform.Wpf.nuspec
build/nuspec/Eto.Platform.XamMac.nuspec
build/nuspec/Eto.Platform.XamMac2.nuspec
build/nuspec/Eto.Platform.iOS.nuspec
build/nuspec/Eto.Serialization.Json.nuspec
build/nuspec/Eto.Serialization.Xaml.nuspec

Fixes generating nupkg files on windows.

Update nuspec files to use proper path separators, now that it works on macOS.

---

build/Build.proj
build/MacTemplate/MacTemplate.targets
build/nuspec/Eto.Forms.nuspec
build/nuspec/Eto.Forms.targets
build/nuspec/Eto.Platform.Mac.nuspec
build/nuspec/Eto.Platform.Mac64.nuspec
build/nuspec/Eto.Platform.XamMac.nuspec
build/nuspec/Eto.Platform.XamMac2.nuspec
build/nuspec/Eto.Serialization.Json.nuspec
build/nuspec/Eto.Serialization.Json.targets
build/nuspec/Eto.Serialization.Xaml.nuspec
build/nuspec/Eto.Serialization.Xaml.targets
src/Eto.Mac/Platform.cs
src/Eto.Serialization.Json/Eto.Serialization.Json.csproj
src/Eto.Serialization.Xaml/Eto.Serialization.Xaml.csproj
src/Eto.Serialization.Xaml/EtoXamlType.cs
src/Eto.sln

- Eto.Serialization.Json and Xaml are now both .NET Standard 1.0
- Include .targets for json/xaml to embed the necessary files (when using sdk style csproj's) and set up DependentUpon
- Only generate mac bundle if not using a specific xamarin.mac or monomac project type

Remove all PCL!

---

src/Eto.Wpf/Forms/Controls/DropDownHandler.cs

In some cases the comboBoxItem is null when updating the list dynamically.

Protect from NRE crash in DropDown/ComboBox

---

src/Shared/PlatformDetect.cs
test/Eto.Test.Gtk/Eto.Test.Gtk.csproj

- Fix platform detection on .NET Core
- Fix getting (proper) calling assembly on Gtk platform
- Set up library fallback path so we can run Eto.Test.Gtk on macOS

Few fixes for .NET Core & Gtk

---

src/Eto.Mac/Forms/Controls/ImageViewHandler.cs

- Not really good to dispose of an image when it is currently being displayed by a user, but this prevents a crash from bad code.

Mac: Prevent crash when disposing an Image in use by ImageView

---

build/MacTemplate/MacTemplate.targets
src/Eto.Direct2D/Platform.cs
src/Eto.Gtk/Platform.cs
src/Eto.Mac/Platform.cs
src/Eto.WinForms/Platform.cs
src/Eto.Wpf/Platform.cs
src/Eto/ExportHandlerAttribute.cs
src/Eto/Platform.cs
src/Eto/PlatformExtension.cs

- Automatically register custom control assembly and platform-specific assembly, if found
- Platform ID's now need to match the platform suffix (e.g. Wpf, WinForms, Mac, XamMac2, etc).
- Added new ExportHandlerAttribute and ExportInitializerAttribute to register handlers and perform logic when loaded with a platform

Make it easier to create custom controls

---

src/Eto.Gtk/Forms/MessageBoxHandler.cs

The constructor for the messagedialog does not take in a text param, but instead a string format. In case you were to use `{ }` in any way this would cause a crash.

[Gtk] Fix setting messagebox text

---

.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
src/Eto.Core.sln

I had to create a separate solution for vscode since it becomes buggy or not even working for several situations:
- having 2 csproj projects look at the same files
- having csproj projects that cannot be loaded
- etc.
This PR is pretty much just QoL change for myself so I can work from VS Code, it shouldn't have any effect on anything else really.

Setup vscode base files for Eto.Gtk

---

src/Eto.Gtk/Forms/Cells/CheckBoxCellHandler.cs
src/Eto.Gtk/Forms/Cells/ComboBoxCellHandler.cs
src/Eto.Gtk/Forms/Cells/CustomCellHandler.cs
src/Eto.Gtk/Forms/Cells/DrawableCellHandler.cs
src/Eto.Gtk/Forms/Cells/ImageViewCellHandler.cs
src/Eto.Gtk/Forms/Cells/ProgressCellHandler.cs
src/Eto.Gtk/Forms/Cells/TextBoxCellHandler.cs

We were either setting it to itself or the default size value which it will be autosized to anyways.

[Gtk] Remove redundant setting of minimal size

---

src/Eto.WinForms/Forms/Controls/GridHandler.cs
src/Eto.Wpf/Forms/Controls/GridColumnHandler.cs

Should be false by default, which should also not trigger GridView.ColumnHeaderClick when false.
Fixes #894

Make GridColumn.Sortable consistent across platforms

---

src/Eto.Gtk/Eto.Gtk.csproj
src/Eto.Gtk/Forms/LinuxNotificationHandler.cs

Stuff done:
- fix up a crash where the object could get disposed before the activate event occurred 
- don't use generics for Delegate marshaling (does not work with .NET Core it seems)
- create a separate notification object for each notification so that something like this does not happen:
```c#
var n = new Notification();
n.ID = 4;
n.Show();
n.ID = 6;
// activate the existing notification, ID is 6
```

[Gtk] Fix Linux NotificationHandler

---

src/Eto.Gtk/Eto.Gtk2.csproj
src/Eto.Mac/Eto.Mac.csproj
src/Eto.Mac/Eto.Mac64.csproj
src/Eto.Mac/Eto.XamMac.csproj
src/Eto.Mac/Eto.XamMac2-modern.csproj
src/Eto.Mac/Eto.XamMac2-net45.csproj
src/Eto.Mac/Forms/Controls/ListBoxHandler.cs
src/Eto.Mac/Forms/Controls/MacControl.cs
src/Eto.Mac/Forms/Controls/MacText.cs
src/Eto.Mac/Forms/Controls/NumericStepperHandler.cs
src/Eto.Mac/Forms/Controls/PasswordBoxHandler.cs
src/Eto.Mac/Forms/Controls/SearchBoxHandler.cs
src/Eto.Mac/Forms/Controls/TextBoxHandler.cs
src/Eto.Mac/Forms/MacFieldEditor.cs
src/Eto.Mac/Forms/MacView.cs
src/Eto.Mac/Forms/MacWindow.cs
src/Eto.Mac/MacConversions.cs
src/Eto.Mac/MacExtensions.cs
src/Eto.Mac/MacHelpers.cs
src/Eto/Forms/Binding/PropertyBinding.cs

- Only create field editor when needed
- Now only create a single field editor per window
- Don't use Font when setting attributed string of a control when font isn't set

Mac: Some tweaks for performance

---

src/Eto.Mac/Forms/Controls/GridViewHandler.cs
src/Eto.Mac/Forms/Controls/TreeGridViewHandler.cs

It would keep the last selection and not respond to selection changes anymore.

Mac: Fix Tree/GridView.ContextMenu when changing the menu when being opened.

---

src/Eto.Mac/Forms/Controls/ButtonHandler.cs
src/Eto.Mac/Forms/Controls/GridHandler.cs
src/Eto.Mac/Forms/Controls/ListBoxHandler.cs
src/Eto.Mac/Forms/Controls/NumericStepperHandler.cs

- GridView, TreeGridView, TreeView, ListBox, Button, and NumericStepper didn't fire these events.

Mac: Fire SizeChanged events for controls that override SetFrameSize

---

src/Eto/Forms/Binding/PropertyBinding.cs
test/Eto.Test/UnitTests/Forms/Binding/ObjectBindingChangedTests.cs
test/Eto.Test/UnitTests/Forms/Binding/PropertyBindingTests.cs

- It worked before even though probably not correct, and don't want to break existing code.
- Also optimize when property is not found to only search once, unless the dataItem type has changed.

Fix regression when binding to internal properties

---

src/Eto.Mac/Forms/Controls/MacButton.cs
src/Eto.Mac/Forms/Menu/ButtonMenuItemHandler.cs
src/Eto.Mac/Forms/Menu/CheckMenuItemHandler.cs
src/Eto.Mac/Forms/Menu/RadioMenuItemHandler.cs
src/Eto.Mac/MacConversions.cs

Use of such APIs may be cause for rejection if submitting to the Mac App Store.
Note that I copy/pasted the ampersand-removal algorithm into the three places where it was needed. If you have a better idea of a better, more common location, please let me know. Thanks!

Remove use of deprecated AppKit API

---

src/Eto.Wpf/Drawing/GraphicsHandler.cs
test/Eto.Test/UnitTests/Drawing/GraphicsTests.cs

- It applied to all drawing operations so changing it to draw a single image didn't work
- Add unit test

Wpf: Fix Graphics.ImageInterpolation

---

src/Eto.Mac/MacHelpers.cs

- Fixes issue when integrating into a native window and you want to get the field editor for the control.

Mac: WeakHandler can be null (e.g. control disposed or other cases)

---

src/Eto.Mac/Forms/Controls/NativeControlHandler.cs

The NSView would never shrink back down if it is sized to a larger size.

Mac: Use FittingSize for native NSView's preferred size

---

src/Eto.Gtk/Drawing/FontFamilyHandler.cs
src/Eto.Gtk/Drawing/FontsHandler.cs
src/Eto.Gtk/Eto.Gtk.csproj
src/Eto.Gtk/Forms/Controls/RichTextAreaHandler.cs
src/Eto.Gtk/GtkConversions.cs
src/Eto.Mac/Drawing/FontTypefaceHandler.cs
src/Eto.Mac/Forms/Controls/RichTextAreaHandler.cs
src/Eto.WinForms/Forms/Controls/RichTextAreaHandler.cs
src/Eto.WinForms/WinConversions.cs
src/Eto.Wpf/CustomControls/FontDialog/fontchooser.xaml
src/Eto.Wpf/CustomControls/FontDialog/fontchooser.xaml.cs
src/Eto.Wpf/Drawing/FontFamilyHandler.cs
src/Eto.Wpf/Drawing/FontHandler.cs
src/Eto.Wpf/Drawing/FontTypefaceHandler.cs
src/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
src/Eto.Wpf/Forms/FontDialogHandler.cs
src/Eto.Wpf/Forms/WpfWindow.cs
src/Eto/Drawing/FontTypeface.cs
src/Eto/Forms/Binding/PropertyBinding.cs
src/Eto/Forms/Controls/FontPicker.cs
src/Eto/Forms/Controls/RichTextArea.cs
src/Eto/Forms/ThemedControls/ThemedFontPickerHandler.cs
test/Eto.Test/Sections/Controls/RichTextAreaSection.cs

Also includes:
- Fix PropertyBinding exception on a class that defines a new property with same name as base class
- Wpf: LogicalPixelSizeChanged should only be fired when the value changes.

RichTextArea FontTypeface implementation

---

src/Eto.Gtk/Eto.Gtk.csproj
src/Eto.Gtk/Forms/ClipboardHandler.cs

By default Gtk only copies a pointer to the data, and not the actual data.

[Gtk] Fix clipboard content getting lost after app quits (fixes #1063)

---

src/Eto.Wpf/Forms/Cells/CustomCellHandler.cs
src/Eto.Wpf/Forms/TableLayoutHandler.cs
test/Eto.Test/Sections/Controls/GridViewSection.cs

- TableLayout would crash with a NRE deep in the bowels of WPF if added to a cell without being created
- Fix using cached controls for a CustomCell with specific identifiers, whereas before it would only use cache if the identifier was null.
- Each custom control needs to have its own CellEventArgs instance as it could be updated or bound to the custom controls
- Fixed CellEventArgs.CellTextColor when the cell is selected but the grid is not focused

Wpf: Fix TableLayout with CustomCell

---

src/Eto.Wpf/Drawing/IconHandler.cs
src/Eto.Wpf/Forms/Controls/ImageViewHandler.cs
src/Eto.Wpf/Forms/WpfWindow.cs
test/Eto.Test/UnitTests/Forms/Controls/ImageViewTests.cs

Not a typical case, but should not crash.  Happened due to Window.LogicalPixelSize reporting 0 when trying to resize the image.
Also added checks to ensure that it won't crash with negative values (e.g. Size = -1, -1), or if scale * size = 0.

Wpf: Fix setting ImageView.Image after window is closed.

---

src/Eto.Gtk/Forms/Menu/ContextMenuHandler.cs
src/Eto.Mac/Forms/Menu/ContextMenuHandler.cs
src/Eto.WinForms/Forms/Menu/ContextMenuHandler.cs
src/Eto.Wpf/Forms/Controls/ExpanderHandler.cs
src/Eto.Wpf/Forms/Controls/SplitterHandler.cs
src/Eto.Wpf/Forms/Menu/CheckMenuItemHandler.cs
src/Eto.Wpf/Forms/Menu/ContextMenuHandler.cs
src/Eto.Wpf/Forms/Menu/RadioMenuItemHandler.cs
src/Eto.Wpf/PropertyChangeNotifier.cs
src/Eto/Forms/Menu/ContextMenu.cs
test/Eto.Test/Sections/Behaviors/ContextMenuSection.cs

Closed event now triggers *after* the menu item's click event, whereas the new Closing event works as Closed did before where it triggers before the menu item's click event.
Also added ability to specify a location relative to the control, or relative to the screen.  Fixes #834

Add ContextMenu.Closing event and Show() overrides for positioning

---

src/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs

Create a copy of the decorations if they are frozen as we are modifying it.

Wpf: Fix crash with RichTextArea when setting text decorations

---

src/Eto/CollectionChangedHandler.cs
src/Eto/Forms/FilterCollection.cs
test/Eto.Test/UnitTests/Forms/Controls/GridViewTests.cs
test/Eto.Test/UnitTests/Forms/FilterCollectionTests.cs

- When responding to NotifyCollectionChangedAction.Reset, the CollectionChangedHandler only removed all items, but should add existing items back.
- Add CollectionChangedHandler.Reset() so that implementations can override and provide a more efficient way (e.g. if you don't need to remove and re-add)
- Added tests for FilterCollection and GridView to ensure the items are indeed shown correctly.

Properly handle Reset for FilterCollection

---

src/Eto.Wpf/Forms/Cells/CustomCellHandler.cs

Direct parent will not be the DataGridCell as we need to add the expander.

Wpf: Fix using a CustomCell as the first column

---

src/Eto.Mac/Forms/MacView.cs
src/Eto.Mac/Forms/MacWindow.cs
src/Eto.Mac/Forms/TableLayoutHandler.cs
test/Eto.Test/UnitTests/Forms/Layout/TableLayoutTests.cs

- Missed a few spots where PositiveInfinity is required vs. int.MaxValue.
- Ensure layout is performed before shown is fired when the form/dialog is not auto sized

Mac: calculate sizes correctly for autosized TableLayout cells

---

src/Eto.Wpf/CustomControls/FontDialog/namedictionaryhelper.cs
src/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
test/Eto.Test/Sections/Controls/RichTextAreaSection.cs

- It only worked with bold, but light, ultralight, semibold, black, etc wouldn't save correctly.
- Updated RichTextArea test so save will update text that will be used for loading

Wpf: Fix RichTextArea saving RTF with different font weights

---

src/Eto.Direct2D/2DConversions.cs
src/Eto.Direct2D/Drawing/GraphicsHandler.cs
src/Eto.WinForms/Drawing/GraphicsHandler.cs

It's a fix to an issue #1141.
1. Direct2D: `ClipBounds` value was incorrect when DPI scaling was on due to rounding and logical problems.
2. WinForms: `ClipBounds` should not depend on PixelOffsetMode value.
3. Direct2D: since the control size is physical size regardess of screen DPI, there is no need to scale WicRenderTarget.

DPI scaling fix in Direct2D engine, ClipBounds property fix in Direct2D and WinForms

---

build/MacTemplate/MacTemplate.targets
build/nuspec/Eto.Platform.Mac.nuspec
build/nuspec/Eto.Platform.Mac64.nuspec
samples/Tutorials/CSharp/Tutorial1/CS.Tutorial1.HelloWorld.csproj
samples/Tutorials/CSharp/Tutorial2/CS.Tutorial2.MenusAndToolbars.csproj
samples/Tutorials/CSharp/Tutorial3/CS.Tutorial3.TableLayout.csproj
samples/Tutorials/CSharp/Tutorial4/CS.Tutorial4.Binding.csproj
samples/Tutorials/FSharp/Tutorial1/FS.Tutorial1.HelloWorld.fsproj
samples/Tutorials/FSharp/Tutorial2/FS.Tutorial2.MenusAndToolbars.fsproj
samples/Tutorials/FSharp/Tutorial3/FS.Tutorial3.TableLayout.fsproj
samples/Tutorials/FSharp/Tutorial4/FS.Tutorial4.Binding.fsproj
test/Eto.Test.Mac/Eto.Test.Mac.csproj
test/Eto.Test.Mac/Eto.Test.Mac64.csproj

This is the one about the lack of CodeTaskFactory for `dotnet build`, following the related thread for [MSBuild issue #616](https://github.com/Microsoft/msbuild/issues/616); so if the Roslyn version of the assembly is not present, a warning is emitted, otherwise use it to generate the task.  Manual testing (by patching the nuget package) allowed an application build and launch using `dotnet` (see [comment](https://github.com/picoe/Eto/issues/1080#issuecomment-388638019) on issue #1080)

Addressing Issues 1076 and 1080

---

src/Eto.WinForms/Eto.WinForms.csproj
src/Eto.WinForms/Forms/HwndFormHandler.cs
src/Eto.WinForms/Win32.dpi.cs
src/Eto.Wpf/Eto.Wpf.csproj
src/Eto.Wpf/Forms/Controls/NumericStepperHandler.cs
src/Eto.Wpf/Forms/ScreenHandler.cs
src/Eto.Wpf/LogicalScreenHelper.cs
test/Eto.Test.Wpf/Eto.Test.Wpf.csproj
test/Eto.Test.Wpf/UnitTests/ScreenTests.cs
test/Eto.Test/Sections/Behaviors/ScreenSection.cs
test/Eto.Test/Sections/UnitTestSection.cs

- Remove recursive algorithm for calculating logical screen locations
- Add tests to verify behaviour
- Fix unit tests to properly show results after all test output
- WinForms should use same Windows 7 API code pack nuget as wpf, which is strong named.

Wpf: Fix possible stack overflow with logical screen locations

---

src/Eto.Mac/Forms/Controls/ButtonHandler.cs

Useful to do things like show the button as a native help button, etc.

Mac: Add ability to set the Button NSBezelStyle in an Eto Style

---

build/Build.props
src/Eto.Gtk/Forms/Controls/DropDownHandler.cs
src/Eto.Mac/Forms/Controls/DropDownHandler.cs
src/Eto.Mac/Forms/Controls/ExpanderHandler.cs
src/Eto.WinForms/Forms/Controls/DropDownHandler.cs
src/Eto.Wpf/Forms/Controls/DropDownHandler.cs
src/Eto/Forms/Controls/ListControl.cs
test/Eto.Test/Sections/Controls/ExpanderSection.cs
test/Eto.Test/UnitTests/Forms/Controls/DropDownTests.cs

This makes DropDown work more consistently across platforms.  The selected item should be kept if it exists in the new data store, and fire appropriate changed events. Also, SelectedValueChanged and SelectedKeyChanged should only trigger if the value is indeed changed.
Also add OS to obj path so it doesn't conflict when using the same code on different platforms at the same time, since the generated .props files appear to save full paths.

DropDown should keep selection when changing DataStore

---

src/Eto.Mac/Drawing/FontHandler.cs
src/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
src/Eto.Wpf/WpfConversions.cs

Wpf: Fix using Regular or Normal font faces in RichTextArea when the weight is not exactly equal.
Wpf: Added extensions to get the name from a System.Windows.Media.LanguageSpecificStringDictionary
Mac: Add constructor for FontHandler that take an NSFont and FontDecorations.

Font handling updates

---

src/Eto.Wpf/WpfConversions.cs

- This avoids rounding issues on different DPI settings (e.g. 225%, 250%) and ensures the size encompasses the entire control.

Wpf: Convert sizes as Math.Ceiling when going to Size/Rectangle

---

src/Eto.Mac/Forms/ApplicationHandler.cs

Ignore it for now.  For some reason even though NSRunLoop.NSDefaultRunLoopMode returns NSString, it gives a warning about using the NextEvent method with string.  Perhaps because it is implicitly converted.

Fix a warning (error in Release) with Xamarin.Mac

---

src/Eto.Direct2D/Drawing/FontTypefaceHandler.cs
src/Eto.Gtk/Drawing/FontTypefaceHandler.cs
src/Eto.Mac/Drawing/FontTypefaceHandler.cs
src/Eto.Mac/Messaging.cs
src/Eto.WinForms/Drawing/FontTypefaceHandler.cs
src/Eto.Wpf/Drawing/FontTypefaceHandler.cs
src/Eto/Drawing/FontTypeface.cs
test/Eto.Test/Sections/Dialogs/FontDialogSection.cs

Implemented for Mac, WPF, and Direct2D.  Other platforms return Name since they don't provide those api's.

Add FontTypeface.LocalizedName

---

src/Eto.Gtk/Forms/Controls/RichTextAreaHandler.cs
src/Eto.Gtk/Forms/Controls/TextAreaHandler.cs
src/Eto.Mac/Forms/Controls/RichTextAreaHandler.cs
src/Eto.Mac/Forms/Controls/TextAreaHandler.cs
src/Eto.Mac/MacConversions.cs
test/Eto.Test/UnitTests/Forms/Controls/RichTextAreaTests.cs
test/Eto.Test/UnitTests/Forms/Controls/TextAreaTests.cs

Make the behaviour consistent across platforms.
- TextChanged should fire when setting RichTextArea.Selection* properties.
- SelectedText should return an empty string when no text is selected.

RichTextArea TextChanged and SelectedText updates

---

src/Eto.WinForms/Forms/HwndFormHandler.cs
src/Eto.WinForms/Win32.cs
src/Eto.Wpf/Forms/Controls/GridHandler.cs

- GridHandler.HasFocus assumed the ParentWindow was WPF
- Showing a message box with no caption uses ParentWindow.Title
- In some cases ParentWindow.Screen is used so it needs to return a value

Wpf: Avoid errors when using a native ParentWindow

---

build/MacTemplate/MacTemplate.targets

Mac: copy files to the correct subdirectory when building .app bundle

---

src/Eto.Gtk/Forms/Controls/TextBoxHandler.cs
src/Eto.Mac/Forms/Controls/MacText.cs
src/Eto.Mac/Forms/Controls/TextBoxHandler.cs
src/Eto.WinForms/Forms/Controls/TextBoxHandler.cs
src/Eto.Wpf/Forms/Controls/TextBoxHandler.cs
src/Eto/Forms/Controls/TextBox.cs
src/Eto/Forms/Controls/TextChangingEventArgs.cs
test/Eto.Test/UnitTests/Forms/Controls/TextBoxTests.cs
test/Eto.Test/UnitTests/Forms/Controls/TextChangingEventArgsTests.cs

- TextChangingEventArgs can be created either with a range or with new/old text
- Trigger TextBox.TextChanging when setting the Text property programatically
- Calculate range/text/newtext based on the information supplied
Fixes #866

Add TextChangingEventArgs.NewText and OldText

---

src/Eto.Mac/Forms/MacView.cs

- MacView.Enabled was abstract so it was required to be overridden.  Change to virtual so things still work, even though the 3rd party libs will need to be updated to use ControlEnabled instead to inherit Enabled from parent.

Mac: fix broken compatibility with some 3rd party libs

---

src/Eto.Mac/Forms/Controls/WebViewHandler.cs
test/Eto.Test.Mac/Info.plist
test/Eto.Test/Sections/Controls/WebViewSection.cs

Switch to a custom implementation of the delegates instead of events as using events causes all delegate methods to be "implemented" (by obj-c standards).

Mac: Fix issue with WebView on Mojave.

---

src/Eto.WinForms/Eto.WinForms.csproj
src/Eto.WinForms/Forms/NativeFormHandler.cs
src/Eto.WinForms/Forms/WindowHandler.cs
src/Eto.WinForms/WinFormsHelpers.cs
src/Eto/Forms/Controls/Control.cs

Also, fix getting parent window of a themed control for any platform.
Fixes #1225

WinForms: Fix getting parent window

---

src/Eto/Forms/Controls/TreeGridView.cs

The original overload should reload children.
Fixes #1236

Fix TreeGridView.ReloadItem regression

---

src/Eto.Mac/Drawing/EtoFontManager.cs
src/Eto.Mac/Drawing/FontFamilyHandler.cs
src/Eto.Mac/Drawing/FontHandler.cs
src/Eto.Mac/Drawing/FontTypefaceHandler.cs
src/Eto.Mac/Eto.Mac.csproj
src/Eto.Mac/Eto.Mac64.csproj
src/Eto.Mac/Eto.XamMac.csproj
src/Eto.Mac/Eto.XamMac2-modern.csproj
src/Eto.Mac/Eto.XamMac2-net45.csproj
src/Eto.Mac/Forms/ApplicationHandler.cs
src/Eto.Mac/Forms/Controls/LinkButtonHandler.cs
src/Eto.Mac/Forms/Controls/SplitterHandler.cs
src/Eto.WinForms/Drawing/FontTypefaceHandler.cs
src/Eto.WinForms/Forms/Controls/RichTextAreaHandler.cs
src/Eto.WinForms/WinConversions.cs
src/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
src/Eto/CollectionChangedHandler.cs
test/Eto.Test/Sections/UnitTestPanel.cs
test/Eto.Test/UnitTests/Forms/Controls/DropDownTests.cs
test/Eto.Test/UnitTests/Forms/Controls/RichTextAreaTests.cs

This includes fonts with Light/UltraLight/Medium/Strong/Narrow variants.  WPF does not by default save/load these from RTF correctly, so we transform the font names when saving or loading.

Fix using font variants with RichTextArea

---

src/Eto.Wpf/Forms/ApplicationHandler.cs

In WPF, DispatcherSynchronizationContext is normally set in Application.Run() ( or Dispatcher.Run()). However, if you do a process that depends on SynchronizationContext before that, we will get unintended behavior. So we fixed it to set it at initialization of Eto.Forms.Application.
Although 'Launching a WPF Window in a Separate Thread'[1] talks about a new thread, it is in the same state as immediately after the main function is started.
[1] [Launching a WPF Window in a Separate Thread, Part 1](http://reedcopsey.com/2011/11/28/launching-a-wpf-window-in-a-separate-thread-part-1/)

[WPF] fix for issue #1041: Corresponds to SynchronizationContext at the Application creation stage.

---

src/Eto.Wpf/Forms/Controls/RichTextAreaHandler.cs
test/Eto.Test/UnitTests/Forms/Controls/RichTextAreaTests.cs

- Saving to RTF should include the same base font as the control
- Loading RTF should not wipe out italic attributes

Wpf: Fix RichTextArea font issues
